package dev.entrelumen;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Rotation;

/**
 * The Ark's astrolabe as data ({@code data/entrelumen/ark_multiblock.json}, generated by
 * {@code art/structures/ark_multiblock.py}; rules in {@code docs/design/ark-multiblock.md}).
 * Positions are relative to the controller's spot. A part is required (the cheap core) or
 * decoration; seven parts are slots: the controller and the six modules. The Ark may face any of
 * the four horizontal directions; rotation {@code r} is {@code Rotation.values()[r]} about the
 * controller's spot, as vanilla {@link BlockPos#rotate} turns it.
 *
 * <p>Pure: callers pass how to read a block and how to normalise it (copper weathering and wax), so
 * the rules run in JUnit without a world.
 */
public final class ArkMultiblock {
  public static final String CONTROLLER = "ark_controller";
  /** The optional places for a beacon on top of the columns; any number of parts may carry it. */
  public static final String BEACON = "beacon";
  /** Properties the game sets from the neighbours when a block is placed: never compared. */
  public static final Set<String> IGNORED = Set.of("shape", "waterlogged", "powered");
  static final String RESOURCE = "/data/entrelumen/ark_multiblock.json";

  /**
   * One position of the shape. {@code state} is the block with any properties, for the guide;
   * {@code properties} are those a placed block must also have (a stair's facing and half), without
   * the ones the game recalculates on placement ({@link #IGNORED}).
   */
  public record Part(BlockPos offset, ResourceLocation block, String state, Map<String, String> properties,
      boolean required, String slot) {
    public Part {
      properties = Collections.unmodifiableMap(new java.util.TreeMap<>(properties));
    }

    public boolean isSlot() {
      return !slot.isEmpty();
    }

    /** Required and not a slot: the core the Ark cannot stand without. */
    public boolean core() {
      return required && slot.isEmpty();
    }
  }

  public record Definition(List<Part> parts, Map<String, BlockPos> slots, List<BlockPos> beacons) {
    public Definition {
      parts = List.copyOf(parts);
      slots = Collections.unmodifiableMap(new LinkedHashMap<>(slots));
      beacons = List.copyOf(beacons);
    }

    /** Every required part: the core and the seven slots. */
    public List<Part> required() {
      return parts.stream().filter(Part::required).toList();
    }

    public List<Part> core() {
      return parts.stream().filter(Part::core).toList();
    }

    public List<Part> decoration() {
      return parts.stream().filter(part -> !part.required() && !part.isSlot()).toList();
    }

    /** The six module slots (every slot but the controller's), in definition order. */
    public Set<String> moduleSlots() {
      Set<String> modules = new TreeSet<>(slots.keySet());
      modules.remove(CONTROLLER);
      return Collections.unmodifiableSet(modules);
    }

    /** Lowest offset of any part: where the shape touches the ground. */
    public int minY() {
      return parts.stream().mapToInt(part -> part.offset().getY()).min().orElse(0);
    }
  }

  /**
   * What a scan found at one anchor: how much of the core is missing, which slots hold their block
   * and whether any position could not be read (an unloaded chunk). {@code missingCore} lists the
   * world positions still to place.
   */
  public record Scan(int coreTotal, List<BlockPos> missingCore, Set<String> filledSlots, int beacons,
      boolean unloaded) {
    public Scan {
      missingCore = List.copyOf(missingCore);
      filledSlots = Collections.unmodifiableSet(new TreeSet<>(filledSlots));
    }

    /** The Ark stands: every required core block is in place and every position was readable. */
    public boolean coreComplete() {
      return !unloaded && missingCore.isEmpty();
    }
  }

  /** An anchor for a shape in the world: the controller's spot and the facing. */
  public record Anchor(BlockPos origin, int rotation) {
    public Anchor {
      origin = origin.immutable();
      rotation = Math.floorMod(rotation, 4);
    }
  }

  private static volatile Definition active;

  private ArkMultiblock() {}

  /** The loaded definition: a datapack's, else the one inside the mod. */
  public static Definition definition() {
    Definition current = active;
    if (current == null) {
      current = builtin();
      active = current;
    }
    return current;
  }

  static void publish(Definition definition) {
    active = definition;
  }

  /** The definition shipped in the mod JAR (also what a client draws as the guide). */
  public static Definition builtin() {
    try (var stream = ArkMultiblock.class.getResourceAsStream(RESOURCE)) {
      if (stream == null) throw new IllegalStateException("Missing " + RESOURCE);
      return parse(JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8)));
    } catch (java.io.IOException e) {
      throw new IllegalStateException("Could not read " + RESOURCE, e);
    }
  }

  /** Reads the definition; rejects duplicates, unknown slots and a missing controller or module. */
  public static Definition parse(JsonElement root) {
    if (!root.isJsonObject() || !root.getAsJsonObject().has("blocks"))
      throw new IllegalArgumentException("Ark multiblock: expected an object with a blocks list");
    List<Part> parts = new ArrayList<>();
    Map<String, BlockPos> slots = new LinkedHashMap<>();
    List<BlockPos> beacons = new ArrayList<>();
    Set<BlockPos> seen = new java.util.HashSet<>();
    for (JsonElement element : root.getAsJsonObject().getAsJsonArray("blocks")) {
      JsonObject entry = element.getAsJsonObject();
      var pos = entry.getAsJsonArray("pos");
      if (pos == null || pos.size() != 3)
        throw new IllegalArgumentException("Ark multiblock: every block needs pos [x, y, z]");
      BlockPos offset = new BlockPos(pos.get(0).getAsInt(), pos.get(1).getAsInt(), pos.get(2).getAsInt());
      if (!seen.add(offset))
        throw new IllegalArgumentException("Ark multiblock: two blocks at " + offset.toShortString());
      String state = entry.get("block").getAsString();
      int bracket = state.indexOf('[');
      ResourceLocation block = ResourceLocation.parse(bracket < 0 ? state : state.substring(0, bracket));
      Map<String, String> properties = new LinkedHashMap<>();
      if (bracket >= 0) {
        if (!state.endsWith("]")) throw new IllegalArgumentException("Ark multiblock: bad block state " + state);
        for (String pair : state.substring(bracket + 1, state.length() - 1).split(",")) {
          int equals = pair.indexOf('=');
          if (equals <= 0) throw new IllegalArgumentException("Ark multiblock: bad block state " + state);
          String name = pair.substring(0, equals).trim();
          if (!IGNORED.contains(name)) properties.put(name, pair.substring(equals + 1).trim());
        }
        // Any stair of the material with the right half: the game turns corners by its neighbours.
        if (block.getPath().endsWith("_stairs")) properties.remove("facing");
      }
      boolean required = entry.has("required") && entry.get("required").getAsBoolean();
      String slot = entry.has("slot") ? entry.get("slot").getAsString() : "";
      if (BEACON.equals(slot)) {
        if (required || !block.equals(ResourceLocation.withDefaultNamespace("beacon")))
          throw new IllegalArgumentException("Ark multiblock: a beacon place holds an optional minecraft:beacon");
        beacons.add(offset);
      } else if (!slot.isEmpty()) {
        if (!ArkRules.SLOTS.contains(slot))
          throw new IllegalArgumentException("Ark multiblock: unknown slot " + slot);
        if (!block.equals(ResourceLocation.fromNamespaceAndPath("entrelumen", slot)))
          throw new IllegalArgumentException("Ark multiblock: slot " + slot + " must hold entrelumen:" + slot);
        if (!required) throw new IllegalArgumentException("Ark multiblock: slot " + slot + " must be required");
        if (slots.put(slot, offset) != null)
          throw new IllegalArgumentException("Ark multiblock: slot " + slot + " appears twice");
      }
      parts.add(new Part(offset, block, state, properties, required, slot));
    }
    for (String slot : ArkRules.SLOTS)
      if (!slots.containsKey(slot)) throw new IllegalArgumentException("Ark multiblock: missing slot " + slot);
    if (!slots.get(CONTROLLER).equals(BlockPos.ZERO))
      throw new IllegalArgumentException("Ark multiblock: positions are relative to the controller at [0, 0, 0]");
    return new Definition(parts, slots, beacons);
  }

  /** Rechiseled's connecting-texture twin of a block counts as the block ({@code X_connecting} is X). */
  public static ResourceLocation withoutConnecting(ResourceLocation id) {
    if (!id.getNamespace().equals("rechiseled") || !id.getPath().endsWith("_connecting")) return id;
    return ResourceLocation.fromNamespaceAndPath("rechiseled", id.getPath().substring(0, id.getPath().length() - "_connecting".length()));
  }

  public static Rotation rotation(int rotation) {
    return Rotation.values()[Math.floorMod(rotation, 4)];
  }

  /** Where an offset of the shape lands for an anchor. */
  public static BlockPos world(Anchor anchor, BlockPos offset) {
    return anchor.origin().offset(offset.rotate(rotation(anchor.rotation())));
  }

  /** The anchor that puts {@code slot} at {@code at} when the Ark faces {@code rotation}. */
  public static Anchor anchorFor(Definition definition, String slot, BlockPos at, int rotation) {
    BlockPos offset = definition.slots().get(slot);
    return new Anchor(at.subtract(offset.rotate(rotation(rotation))), rotation);
  }

  /**
   * How a world is read: whether the block at a position matches a part for an Ark facing
   * {@code rotation}, or null when its chunk is not loaded (it is never asked to load one).
   */
  @FunctionalInterface
  public interface Matcher {
    Boolean matches(BlockPos at, Part part, int rotation);
  }

  /**
   * A matcher over block ids and properties. {@code blockAt} returns a block's id (null when
   * unloaded); {@code property} returns a block property's value there; {@code normalise} maps a
   * block id to the id its family compares with (weathered or waxed copper to plain copper). A
   * {@code facing} is turned with the Ark.
   */
  public static Matcher matcher(Function<BlockPos, ResourceLocation> blockAt,
      java.util.function.BiFunction<BlockPos, String, String> property, UnaryOperator<ResourceLocation> normalise) {
    return (at, part, rotation) -> {
      ResourceLocation found = blockAt.apply(at);
      if (found == null) return null;
      if (!normalise.apply(found).equals(normalise.apply(part.block()))) return false;
      for (var expected : part.properties().entrySet()) {
        String value = expected.getValue();
        if (expected.getKey().equals("facing")) value = turn(value, rotation);
        if (!value.equals(property.apply(at, expected.getKey()))) return false;
      }
      return true;
    };
  }

  /** A horizontal facing turned with the Ark; other values stay. */
  static String turn(String facing, int rotation) {
    var direction = net.minecraft.core.Direction.byName(facing);
    if (direction == null || direction.getAxis().isVertical()) return facing;
    return rotation(rotation).rotate(direction).getSerializedName();
  }

  public static Scan scan(Definition definition, Anchor anchor, Function<BlockPos, ResourceLocation> blockAt,
      UnaryOperator<ResourceLocation> normalise) {
    return scan(definition, anchor, matcher(blockAt, (at, name) -> null, normalise));
  }

  /** Reads the shape at an anchor. */
  public static Scan scan(Definition definition, Anchor anchor, Matcher matcher) {
    int total = 0;
    List<BlockPos> missing = new ArrayList<>();
    Set<String> filled = new TreeSet<>();
    int beacons = 0;
    boolean unloaded = false;
    for (Part part : definition.parts()) {
      if (BEACON.equals(part.slot())) {
        Boolean found = matcher.matches(world(anchor, part.offset()), part, anchor.rotation());
        if (Boolean.TRUE.equals(found)) beacons++;
        continue;
      }
      if (!part.required()) continue;
      BlockPos at = world(anchor, part.offset());
      Boolean found = matcher.matches(at, part, anchor.rotation());
      if (part.core()) total++;
      if (found == null) {
        unloaded = true;
        if (part.core()) missing.add(at);
        continue;
      }
      boolean matches = found;
      if (part.isSlot()) {
        if (matches) filled.add(part.slot());
      } else if (!matches) {
        missing.add(at);
      }
    }
    return new Scan(total, missing, filled, beacons, unloaded);
  }

  /**
   * The best of the four facings for a slot block at {@code at}: the one whose core is most complete,
   * then the one with most slots filled, then the lowest rotation (the facing of the drawings).
   */
  public static Anchor locate(Definition definition, String slot, BlockPos at, Matcher matcher) {
    Anchor best = null;
    long bestScore = Long.MIN_VALUE;
    for (int rotation = 0; rotation < 4; rotation++) {
      Anchor anchor = anchorFor(definition, slot, at, rotation);
      Scan scan = scan(definition, anchor, matcher);
      long score = (long) (scan.coreTotal() - scan.missingCore().size()) * 16 + scan.filledSlots().size();
      if (score > bestScore) {
        bestScore = score;
        best = anchor;
      }
    }
    return best;
  }

  /** Whether a world position is one of the shape's parts for this anchor (any part, required or not). */
  public static boolean contains(Definition definition, Anchor anchor, BlockPos pos) {
    for (Part part : definition.parts())
      if (world(anchor, part.offset()).equals(pos)) return true;
    return false;
  }

  /** The slot at a world position for this anchor, or empty. */
  public static String slotAt(Definition definition, Anchor anchor, BlockPos pos) {
    for (var entry : definition.slots().entrySet())
      if (world(anchor, entry.getValue()).equals(pos)) return entry.getKey();
    return "";
  }
}
