package dev.entrelumen;

import java.util.Collections;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import com.mojang.serialization.Codec;
import net.minecraft.advancements.critereon.ItemSubPredicate;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.ArmorMaterial;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Tier;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.block.Block;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.common.NeoForgeMod;
import net.neoforged.neoforge.event.ItemAttributeModifierEvent;
import net.neoforged.neoforge.event.entity.living.LivingEquipmentChangeEvent;
import net.neoforged.neoforge.event.entity.living.LivingFallEvent;
import net.neoforged.neoforge.event.tick.PlayerTickEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * The luminous content: six Luminosities, the Luminous Ingot and the luminous armour and tools,
 * plus the per-player light repair and set bonus. Numbers live in {@link LuminousRules}; item
 * behaviour in {@link LuminousGear}. Recipes are pack data generated by
 * {@code tools/generate_family_balance.py --family luminous}; the Luminosities have none (Solsticio's
 * native villagers will sell them).
 *
 * <p>Silent Gear pieces made with the Luminous Ingot carry the {@code entrelumen:radiant} trait
 * ({@link SilentGearCompat}) and count as luminous: any mix of four lit luminous or radiant armour
 * pieces is a full set. The full set flies through NeoForge's {@code creative_flight} attribute, never
 * through {@code abilities.mayfly}, so jetpacks, rings and creative mode keep their own flight. The
 * {@code entrelumen:radiant} item sub-predicate lets LambDynamicLights data light every lit piece.
 */
public final class Luminous {
  static final DeferredRegister.Items ITEMS = DeferredRegister.createItems("entrelumen");
  static final DeferredRegister<ArmorMaterial> ARMOR_MATERIALS =
      DeferredRegister.create(Registries.ARMOR_MATERIAL, "entrelumen");

  /** Empty: a luminous tool can harvest every block its kind mines. */
  public static final TagKey<Block> INCORRECT_FOR_LUMINOUS_TOOL = BlockTags.create(id("incorrect_for_luminous_tool"));
  public static final TagKey<Item> LUMINOSITIES_TAG = ItemTags.create(id("luminosities"));
  public static final TagKey<Item> GEAR_TAG = ItemTags.create(id("luminous_gear"));
  /** Persistent-data flag: the night vision on this player was granted by the set. */
  static final String NIGHT_VISION_FLAG = "entrelumen.luminous_night_vision";
  /** Transient creative_flight modifier of the full set. */
  public static final ResourceLocation FLIGHT = id("luminous_flight");

  static final DeferredRegister<ItemSubPredicate.Type<?>> PREDICATES =
      DeferredRegister.create(Registries.ITEM_SUB_PREDICATE_TYPE, "entrelumen");
  /** {@code "predicates": {"entrelumen:radiant": {}}}: a lit luminous piece or a working radiant Silent Gear piece. */
  public static final DeferredHolder<ItemSubPredicate.Type<?>, ItemSubPredicate.Type<Radiant>> RADIANT =
      PREDICATES.register("radiant", () -> new ItemSubPredicate.Type<>(Radiant.CODEC));

  public record Radiant() implements ItemSubPredicate {
    public static final Radiant INSTANCE = new Radiant();
    public static final Codec<Radiant> CODEC = Codec.unit(INSTANCE);

    @Override
    public boolean matches(ItemStack stack) {
      return shining(stack);
    }
  }

  public static final Map<LuminousRules.Discipline, DeferredItem<LuminousGear.Luminosity>> LUMINOSITIES;

  static {
    Map<LuminousRules.Discipline, DeferredItem<LuminousGear.Luminosity>> luminosities =
        new EnumMap<>(LuminousRules.Discipline.class);
    for (var discipline : LuminousRules.Discipline.values())
      luminosities.put(discipline, ITEMS.register(discipline.item(),
          () -> new LuminousGear.Luminosity(discipline, new Item.Properties().rarity(Rarity.RARE))));
    LUMINOSITIES = Collections.unmodifiableMap(luminosities);
  }

  public static final DeferredItem<LuminousGear.Ingot> INGOT = ITEMS.register("luminous_ingot",
      () -> new LuminousGear.Ingot(new Item.Properties().rarity(Rarity.EPIC).fireResistant()));

  public static final DeferredHolder<ArmorMaterial, ArmorMaterial> MATERIAL = ARMOR_MATERIALS.register("luminous",
      () -> new ArmorMaterial(
          Map.of(ArmorItem.Type.HELMET, LuminousRules.HELMET_ARMOR,
              ArmorItem.Type.CHESTPLATE, LuminousRules.CHESTPLATE_ARMOR,
              ArmorItem.Type.LEGGINGS, LuminousRules.LEGGINGS_ARMOR,
              ArmorItem.Type.BOOTS, LuminousRules.BOOTS_ARMOR),
          LuminousRules.ENCHANTABILITY, SoundEvents.ARMOR_EQUIP_GOLD,
          () -> Ingredient.of(INGOT.get()),
          // entrelumen:textures/models/armor/luminous_layer_1.png and luminous_layer_2.png
          List.of(new ArmorMaterial.Layer(id("luminous"))),
          LuminousRules.TOUGHNESS, LuminousRules.KNOCKBACK_RESISTANCE));

  /** The luminous tool tier. */
  public static final Tier TIER = new Tier() {
    @Override
    public int getUses() {
      return LuminousRules.TOOL_USES;
    }

    @Override
    public float getSpeed() {
      return LuminousRules.TOOL_SPEED;
    }

    @Override
    public float getAttackDamageBonus() {
      return LuminousRules.TOOL_ATTACK_BONUS;
    }

    @Override
    public TagKey<Block> getIncorrectBlocksForDrops() {
      return INCORRECT_FOR_LUMINOUS_TOOL;
    }

    @Override
    public int getEnchantmentValue() {
      return LuminousRules.ENCHANTABILITY;
    }

    @Override
    public Ingredient getRepairIngredient() {
      return Ingredient.of(INGOT.get());
    }
  };

  public static final DeferredItem<LuminousGear.Armor> HELMET = armor("luminous_helmet", ArmorItem.Type.HELMET);
  public static final DeferredItem<LuminousGear.Armor> CHESTPLATE = armor("luminous_chestplate", ArmorItem.Type.CHESTPLATE);
  public static final DeferredItem<LuminousGear.Armor> LEGGINGS = armor("luminous_leggings", ArmorItem.Type.LEGGINGS);
  public static final DeferredItem<LuminousGear.Armor> BOOTS = armor("luminous_boots", ArmorItem.Type.BOOTS);
  public static final DeferredItem<LuminousGear.Sword> SWORD = ITEMS.register("luminous_sword",
      () -> new LuminousGear.Sword(gear()));
  public static final DeferredItem<LuminousGear.Pickaxe> PICKAXE = ITEMS.register("luminous_pickaxe",
      () -> new LuminousGear.Pickaxe(gear()));
  public static final DeferredItem<LuminousGear.Axe> AXE = ITEMS.register("luminous_axe",
      () -> new LuminousGear.Axe(gear()));
  public static final DeferredItem<LuminousGear.Shovel> SHOVEL = ITEMS.register("luminous_shovel",
      () -> new LuminousGear.Shovel(gear()));
  public static final DeferredItem<LuminousGear.Hoe> HOE = ITEMS.register("luminous_hoe",
      () -> new LuminousGear.Hoe(gear()));

  /** Armour worn in head, chest, legs and feet order. */
  static final List<EquipmentSlot> SET_SLOTS =
      List.of(EquipmentSlot.HEAD, EquipmentSlot.CHEST, EquipmentSlot.LEGS, EquipmentSlot.FEET);

  private Luminous() {}

  static ResourceLocation id(String path) {
    return ResourceLocation.fromNamespaceAndPath("entrelumen", path);
  }

  private static Item.Properties gear() {
    return new Item.Properties().rarity(Rarity.EPIC).fireResistant();
  }

  private static DeferredItem<LuminousGear.Armor> armor(String name, ArmorItem.Type type) {
    return ITEMS.register(name, () -> new LuminousGear.Armor(MATERIAL, type,
        gear().durability(type.getDurability(LuminousRules.ARMOR_DURABILITY_FACTOR))));
  }

  static void register(IEventBus bus) {
    ITEMS.register(bus);
    ARMOR_MATERIALS.register(bus);
    PREDICATES.register(bus);
    NeoForge.EVENT_BUS.addListener(Luminous::playerTick);
    NeoForge.EVENT_BUS.addListener(Luminous::equipmentChanged);
    NeoForge.EVENT_BUS.addListener(Luminous::fall);
    NeoForge.EVENT_BUS.addListener(Luminous::dimAttributes);
  }

  /** A dimmed piece gives no armour, toughness, knockback resistance, attack or speed. */
  static void dimAttributes(ItemAttributeModifierEvent event) {
    if (LuminousGear.dimmed(event.getItemStack())) event.clearModifiers();
  }

  private static void playerTick(PlayerTickEvent.Post event) {
    if (event.getEntity() instanceof ServerPlayer player && player.tickCount % LuminousRules.INTERVAL_TICKS == 0)
      refresh(player);
  }

  /** One interval of light repair and set bonus for a player; called every second on the server. */
  public static void refresh(ServerPlayer player) {
    repair(player.getInventory(), brightness(player));
    setBonus(player);
  }

  /** Raw brightness at the player's eyes: block light, or sky light darkened by the time of day. */
  public static int brightness(LivingEntity entity) {
    return entity.level().getMaxLocalRawBrightness(BlockPos.containing(entity.getEyePosition()));
  }

  /** A luminous piece that is lit, or a Silent Gear piece of the luminous material that works. */
  public static boolean shining(ItemStack stack) {
    if (stack.getItem() instanceof LuminousGear.Piece) return !LuminousGear.dimmed(stack);
    return SilentGearCompat.radiant(stack);
  }

  /** Mended by light: every luminous piece and every radiant Silent Gear piece, lit or not. */
  static boolean mendable(ItemStack stack) {
    return stack.getItem() instanceof LuminousGear.Piece || SilentGearCompat.radiantLevel(stack) > 0;
  }

  /** Repairs every damaged luminous piece in the inventory; returns the points restored. */
  public static int repair(Inventory inventory, int brightness) {
    int restored = 0;
    for (var list : List.of(inventory.items, inventory.armor, inventory.offhand))
      for (ItemStack stack : list) {
        if (!stack.isDamaged() || !mendable(stack)) continue;
        int amount = LuminousRules.lightRepair(brightness, stack.getDamageValue());
        if (amount > 0) {
          stack.setDamageValue(stack.getDamageValue() - amount);
          restored += amount;
        }
      }
    return restored;
  }

  /**
   * True when all four armour slots hold armour of the right type that is luminous (lit) or radiant
   * Silent Gear (working); the two kinds mix freely.
   */
  public static boolean fullSet(LivingEntity entity) {
    boolean[] worn = new boolean[4];
    boolean[] dimmed = new boolean[4];
    for (int i = 0; i < 4; i++) {
      ItemStack stack = entity.getItemBySlot(SET_SLOTS.get(i));
      worn[i] = stack.getItem() instanceof ArmorItem armor && armor.getEquipmentSlot() == SET_SLOTS.get(i)
          && (stack.getItem() instanceof LuminousGear.Armor || SilentGearCompat.radiantLevel(stack) > 0);
      dimmed[i] = worn[i] && !shining(stack);
    }
    return LuminousRules.fullSet(worn, dimmed);
  }

  /** Re-evaluates the set as soon as a player's equipment changes, so flight never lingers. */
  static void equipmentChanged(LivingEquipmentChangeEvent event) {
    if (event.getEntity() instanceof ServerPlayer player && event.getSlot().isArmor()) setBonus(player);
  }

  /** True while the full set's creative_flight modifier is on the player. */
  public static boolean setFlight(ServerPlayer player) {
    var attribute = player.getAttribute(NeoForgeMod.CREATIVE_FLIGHT);
    return attribute != null && attribute.hasModifier(FLIGHT);
  }

  /**
   * Adds or removes the full set's flight. Only this modifier is touched: other sources of flight
   * (creative, jetpacks, rings, other modifiers) keep working. A player left flying in mid-air by
   * losing the set gets slow falling instead of a lethal drop.
   */
  static void flight(ServerPlayer player, boolean granted) {
    var attribute = player.getAttribute(NeoForgeMod.CREATIVE_FLIGHT);
    if (attribute == null || attribute.hasModifier(FLIGHT) == granted) return;
    if (granted) {
      attribute.addTransientModifier(new AttributeModifier(FLIGHT, 1.0, AttributeModifier.Operation.ADD_VALUE));
      return;
    }
    boolean wasFlying = player.getAbilities().flying;
    attribute.removeModifier(FLIGHT);
    if (wasFlying && !player.mayFly()) {
      player.getAbilities().flying = false;
      player.onUpdateAbilities();
      player.addEffect(new MobEffectInstance(MobEffects.SLOW_FALLING, LuminousRules.FLIGHT_LANDING_TICKS, 0, false, false, true));
    }
  }

  /** Flight and night vision while the full set shines; night vision goes only if the set gave it. */
  static void setBonus(ServerPlayer player) {
    var data = player.getPersistentData();
    boolean full = fullSet(player);
    flight(player, full);
    if (full) {
      player.addEffect(new MobEffectInstance(MobEffects.NIGHT_VISION, LuminousRules.NIGHT_VISION_TICKS, 0,
          true, false, true));
      data.putBoolean(NIGHT_VISION_FLAG, true);
    } else if (data.getBoolean(NIGHT_VISION_FLAG)) {
      var effect = player.getEffect(MobEffects.NIGHT_VISION);
      if (effect != null && effect.isAmbient() && effect.getDuration() <= LuminousRules.NIGHT_VISION_TICKS)
        player.removeEffect(MobEffects.NIGHT_VISION);
      data.remove(NIGHT_VISION_FLAG);
    }
  }

  /** The full set cancels fall damage for whoever wears it. */
  static void fall(LivingFallEvent event) {
    if (fullSet(event.getEntity())) event.setDamageMultiplier(0f);
  }
}
