package dev.entrelumen;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Rotation;

/**
 * Terra's hydroponic garden, a 3 x 2 x 2 engine, as data ({@code data/entrelumen/terra_garden.json},
 * generated by {@code art/structures/terra_garden.py}; design in {@code docs/design/terra-garden.md}). Positions are
 * relative to the core; the drawing faces south, so the core looks south at rotation 0. Rotation
 * {@code r} is {@code Rotation.values()[r]} about the core, as {@link BlockPos#rotate} turns it: the
 * garden may face any of the four horizontal directions, and being mirror-symmetric it also reads the
 * same mirrored.
 *
 * <p>Pure: callers pass how to read a block (its id and properties, or null when its chunk is not
 * loaded) and how to normalise an id, so the rules run in JUnit without a world. Every position is
 * required; the plan's ghost shows exactly the blocks the core checks.
 */
public final class TerraGardenLayout {
  public static final String RESOURCE = "/data/entrelumen/terra_garden.json";
  public static final ResourceLocation CORE = ResourceLocation.fromNamespaceAndPath("entrelumen", "terra_garden_core");
  /** Where the harvest leaves the engine. */
  public static final ResourceLocation OUTLET = ResourceLocation.fromNamespaceAndPath("entrelumen", "terra_garden_outlet");
  /**
   * Properties never compared: the ones the game sets from neighbours or time (a stair's shape, water,
   * redstone power, a copper bulb's light, a piston's head, a member's formed look, a vine's age and berries, a pillar's axis,
   * leaves' distance and persistence). The ghost still draws the state the drawing asks for.
   */
  public static final Set<String> IGNORED = Set.of("shape", "waterlogged", "powered", "lit", "extended", "formed", "age",
      "berries", "axis", "distance", "persistent");

  /** One position: the block with any properties (for the ghost) and those a placed block must match. */
  public record Part(BlockPos offset, ResourceLocation block, String state, Map<String, String> properties) {
    public Part {
      offset = offset.immutable();
      properties = Collections.unmodifiableMap(new TreeMap<>(properties));
    }

    public boolean core() {
      return block.equals(CORE);
    }
  }

  public record Definition(List<Part> parts) {
    public Definition {
      parts = List.copyOf(parts);
    }

    public int size() {
      return parts.size();
    }

    /** How many parts hold this block (by id). */
    public long count(ResourceLocation block) {
      return parts.stream().filter(p -> p.block().equals(block)).count();
    }
  }

  /** Reads a world position: the block's id there, or null when its chunk is not loaded. */
  @FunctionalInterface
  public interface Reader {
    ResourceLocation blockAt(BlockPos pos);
  }

  /** What one check found: the positions still wrong (world coordinates) and whether any was unreadable. */
  public record Scan(int rotation, List<BlockPos> missing, boolean unloaded) {
    public Scan {
      missing = List.copyOf(missing);
    }

    public boolean complete() {
      return !unloaded && missing.isEmpty();
    }
  }

  private static volatile Definition builtin;

  private TerraGardenLayout() {}

  /** The layout inside the mod JAR (also what the plan projects). */
  public static Definition builtin() {
    Definition current = builtin;
    if (current == null) {
      try (var stream = TerraGardenLayout.class.getResourceAsStream(RESOURCE)) {
        if (stream == null) throw new IllegalStateException("Missing " + RESOURCE);
        current = parse(JsonParser.parseReader(new InputStreamReader(stream, StandardCharsets.UTF_8)));
      } catch (java.io.IOException e) {
        throw new IllegalStateException("Could not read " + RESOURCE, e);
      }
      builtin = current;
    }
    return current;
  }

  /** Reads a layout; rejects duplicates, a missing core or a core that is not at [0, 0, 0]. */
  public static Definition parse(JsonElement root) {
    if (!root.isJsonObject() || !root.getAsJsonObject().has("blocks"))
      throw new IllegalArgumentException("Terra garden: expected an object with a blocks list");
    List<Part> parts = new ArrayList<>();
    Set<BlockPos> seen = new HashSet<>();
    int cores = 0;
    for (JsonElement element : root.getAsJsonObject().getAsJsonArray("blocks")) {
      JsonObject entry = element.getAsJsonObject();
      var pos = entry.getAsJsonArray("pos");
      if (pos == null || pos.size() != 3) throw new IllegalArgumentException("Terra garden: every block needs pos [x, y, z]");
      BlockPos offset = new BlockPos(pos.get(0).getAsInt(), pos.get(1).getAsInt(), pos.get(2).getAsInt());
      if (!seen.add(offset)) throw new IllegalArgumentException("Terra garden: two blocks at " + offset.toShortString());
      String state = entry.get("block").getAsString();
      int bracket = state.indexOf('[');
      ResourceLocation block = ResourceLocation.parse(bracket < 0 ? state : state.substring(0, bracket));
      Map<String, String> properties = new LinkedHashMap<>();
      if (bracket >= 0) {
        if (!state.endsWith("]")) throw new IllegalArgumentException("Terra garden: bad block state " + state);
        for (String pair : state.substring(bracket + 1, state.length() - 1).split(",")) {
          int equals = pair.indexOf('=');
          if (equals <= 0) throw new IllegalArgumentException("Terra garden: bad block state " + state);
          String name = pair.substring(0, equals).trim();
          if (!IGNORED.contains(name)) properties.put(name, pair.substring(equals + 1).trim());
        }
        // Any stair of the material with the right half: which way an arch's shoulder leans is looks only.
        if (block.getPath().endsWith("_stairs")) properties.remove("facing");
      }
      Part part = new Part(offset, block, state, properties);
      if (part.core()) {
        cores++;
        if (!offset.equals(BlockPos.ZERO))
          throw new IllegalArgumentException("Terra garden: positions are relative to the core at [0, 0, 0]");
      }
      parts.add(part);
    }
    if (cores != 1) throw new IllegalArgumentException("Terra garden: exactly one core, found " + cores);
    return new Definition(parts);
  }

  public static Rotation rotation(int rotation) {
    return Rotation.values()[Math.floorMod(rotation, 4)];
  }

  /** The direction the core looks at rotation {@code r}: the drawing's south, turned. */
  public static Direction front(int rotation) {
    return rotation(rotation).rotate(Direction.SOUTH);
  }

  /** The rotation whose front is {@code facing} (a horizontal direction). */
  public static int rotationFacing(Direction facing) {
    for (int r = 0; r < 4; r++)
      if (front(r) == facing) return r;
    throw new IllegalArgumentException("Not horizontal: " + facing);
  }

  /** Where an offset lands for a core at {@code core} and rotation {@code r}. */
  public static BlockPos world(BlockPos core, int rotation, BlockPos offset) {
    return core.offset(offset.rotate(rotation(rotation)));
  }

  /** A horizontal facing turned with the garden; other values stay. */
  static String turn(String facing, int rotation) {
    Direction direction = Direction.byName(facing);
    if (direction == null || direction.getAxis().isVertical()) return facing;
    return rotation(rotation).rotate(direction).getSerializedName();
  }

  /**
   * Whether a placed block matches a part at rotation {@code r}: the same normalised block (copper at any
   * oxidation stage or waxed, a grown vine as a vine) and every kept property, with a facing turned.
   * {@code property} reads a property's value at the position (null when the block has none).
   */
  public static boolean matches(Part part, ResourceLocation found, Function<String, String> property,
      int rotation, UnaryOperator<ResourceLocation> normalise) {
    if (!normalise.apply(found).equals(normalise.apply(part.block()))) return false;
    for (var expected : part.properties().entrySet()) {
      String value = expected.getKey().equals("facing") ? turn(expected.getValue(), rotation) : expected.getValue();
      if (!value.equals(property.apply(expected.getKey()))) return false;
    }
    return true;
  }

  /**
   * Checks the whole garden for a core at {@code core} and rotation {@code r}. {@code property} reads a
   * property at a world position. It never loads a chunk: an unreadable position makes the scan
   * incomplete.
   */
  public static Scan scan(Definition definition, BlockPos core, int rotation, Reader reader,
      BiFunction<BlockPos, String, String> property, UnaryOperator<ResourceLocation> normalise) {
    List<BlockPos> missing = new ArrayList<>();
    boolean unloaded = false;
    for (Part part : definition.parts()) {
      BlockPos at = world(core, rotation, part.offset());
      ResourceLocation found = reader.blockAt(at);
      if (found == null) {
        unloaded = true;
        missing.add(at);
        continue;
      }
      if (!matches(part, found, name -> property.apply(at, name), rotation, normalise)) missing.add(at);
    }
    return new Scan(Math.floorMod(rotation, 4), missing, unloaded);
  }

  /**
   * The first rotation (starting from {@code preferred}, the way the core looks) under which the garden
   * stands complete, or the best partial scan (fewest missing) when none does.
   */
  public static Scan find(Definition definition, BlockPos core, int preferred, Reader reader,
      BiFunction<BlockPos, String, String> property, UnaryOperator<ResourceLocation> normalise) {
    Scan best = null;
    for (int i = 0; i < 4; i++) {
      Scan scan = scan(definition, core, preferred + i, reader, property, normalise);
      if (scan.complete()) return scan;
      if (best == null || scan.missing().size() < best.missing().size()) best = scan;
    }
    return best;
  }

  /** Whether a world position is one of the garden's positions for a core and rotation. */
  public static boolean contains(Definition definition, BlockPos core, int rotation, BlockPos pos) {
    for (Part part : definition.parts())
      if (world(core, rotation, part.offset()).equals(pos)) return true;
    return false;
  }
}
