// Generated by tools/generate_family_balance.py --family pingpong7; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenPingpong7Signature = "30a7b3d31dc7f912245f48e7a37e0341209a867ecf99f3c62d6a90f8c37b6907";
const entrelumenPingpong7Sources = {"MysticalAgradditions-1.21.1-8.0.14.jar":"8f65713181cdb61f67637c49f7200f8fb5b8fef2aaf314c4da116d60077c9e46","me_beam_former-1.21.1-1.3.0.jar":"cfd96ad8ec16a8f3286cb8ad33252ead0379bb83ed910980474889022d76dcb3"};
const entrelumenPingpong7Rows = [{"id":"mysticalagradditions:insanium_block_combine","output":"mysticalagradditions:insanium_block","component":"entrelumen:luminosity_nature","act":"VI","json":{"type":"crafting_shaped","pattern":[" Z ","ECE"," E "],"key":{"E":{"item":"mysticalagriculture:supremium_block"},"C":{"item":"mysticalagriculture:master_infusion_crystal"},"Z":{"item":"entrelumen:luminosity_nature"}},"result":{"id":"mysticalagradditions:insanium_block"}}}];
const entrelumenPingpong7Removals = ["mysticalagradditions:insanium_essence", "me_beam_former:wireless_energy_tower"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenPingpong7Rows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenPingpong7Removals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenPingpong7Signature, missing: missing}));
    throw new Error('ENTRELUMEN_PINGPONG7_BALANCE preflight failed; native recipes were not changed');
  }
  entrelumenPingpong7Rows.forEach(row => {
    event.remove({id: row.id});
    event.custom(row.json).id(row.id);
  });
  entrelumenPingpong7Removals.forEach(id => event.remove({id: id}));
  console.info('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: 'registered', signature: entrelumenPingpong7Signature, changed: entrelumenPingpong7Rows.length,
    removed: entrelumenPingpong7Removals.length - absent.length, alreadyAbsent: absent}));
});
function entrelumenPingpong7FieldCheck(event, row) {
  // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
  var found = 0;
  try {
    var stack = Item.of(row.component);
    event.forEachRecipe({id: row.id}, holder => {
      holder.value()[row.field].forEach(ingredient => { if (ingredient.test(stack)) found++; });
    });
  } catch (error) {
    console.warn('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: 'field-check-error', recipe: row.id, error: String(error)}));
    return -1;
  }
  return found;
}
ServerEvents.afterRecipes(event => {
  var failed = [];
  entrelumenPingpong7Rows.forEach(row => {
    var loaded = event.countRecipes({id: row.id, output: row.output});
    var staged = event.countRecipes({id: row.id, input: row.component});
    if (staged === 0 && row.field) staged = entrelumenPingpong7FieldCheck(event, row);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenPingpong7Removals.forEach(id => { var left = event.countRecipes({id: id}); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenPingpong7Signature, checked: entrelumenPingpong7Rows.length + entrelumenPingpong7Removals.length, failed: failed}));
});
