// Generated by tools/generate_cooking_provisions.py --write.
// Additive native crafting: original ration and item remainders remain intact.
const entrelumenCookingSignature = "8fbeef6d5f86db49d63d687e3d167cf6b749a223e35d5ab93d9568f2c0c7e16c";
const entrelumenCookingSources = [{"filename":"herbsandharvest-1.21.1-19.jar","sha256":"d2aa1d4bd73df669ae4d72df9a1854ac2f309e33aec872cb49f876de04d626d2"},{"filename":"pamhc2foodcore-NEOFORGE-1.21.1-1.0.4.jar","sha256":"acd5dd380eafc3f317b67231a2355c204cab254dfdf4ab1f25c084fdd3d317b9"},{"filename":"pamhc2trees-NEOFORGE-1.21.1-1.0.9.jar","sha256":"64c34129468b0d75738cf0faf667a52067d2db1e72ee8564c0a8f850bbf154c7"},{"filename":"sushigocrafting-1.21-0.6.5.jar","sha256":"5b59c5f71609fd06b47afbf357360c65d47905efda59ad64b27e03617ab9d8ce"},{"filename":"storagedelight-26.07.01a-1.21-neoforge.jar","sha256":"ea43e971afe557eaeadcc26536cf58664507e43a2c9086e7f57170eb4b5cda0c"}];
const entrelumenCookingRecipes = [{"id":"entrelumen:cooking_provisions/homestead_chicken","json":{"type":"minecraft:crafting_shaped","category":"misc","pattern":[" A ","B B"," A "],"key":{"A":{"item":"farmersdelight:vegetable_soup"},"B":{"item":"pamhc2foodcore:chickendinneritem"}},"result":{"id":"entrelumen:ration_bundle","count":1}}},{"id":"entrelumen:cooking_provisions/field_supper","json":{"type":"minecraft:crafting_shaped","category":"misc","pattern":[" A ","B B"," A "],"key":{"A":{"item":"farmersdelight:fish_stew"},"B":{"item":"herbsandharvest:beef_cheddar"}},"result":{"id":"entrelumen:ration_bundle","count":1}}}];
ServerEvents.recipes(event => {
  const errors = [];
  entrelumenCookingRecipes.forEach(row => {
    if (event.containsRecipe({id: row.id})) errors.push({recipe: row.id, collision: true});
    [row.json.result.id].concat(Object.keys(row.json.key).map(k => row.json.key[k].item)).forEach(id => {
      if (!Item.exists(id)) errors.push({recipe: row.id, missingItem: id});
    });
  });
  if (errors.length) {
    console.error('[ENTRELUMEN_COOKING] ' + JSON.stringify({status: 'failed-preflight', errors: errors}));
    throw new Error('Cooking provisions preflight failed');
  }
  entrelumenCookingRecipes.forEach(row => event.custom(row.json).id(row.id));
  console.info('[ENTRELUMEN_COOKING] ' + JSON.stringify({status: 'registered', signature: entrelumenCookingSignature, recipes: entrelumenCookingRecipes.length}));
});
ServerEvents.afterRecipes(event => {
  const checked = entrelumenCookingRecipes.concat([{id: 'entrelumen:integration/travelling_pantry', json: {result: {id: 'entrelumen:ration_bundle'}}}]);
  const failed = checked.filter(row => event.countRecipes({id: row.id, output: row.json.result.id}) !== 1).map(row => row.id);
  const receipt = {status: failed.length ? 'failed-loaded-check' : 'loaded-output-check-only', signature: entrelumenCookingSignature, checked: checked.length, failed: failed};
  if (failed.length) console.error('[ENTRELUMEN_COOKING] ' + JSON.stringify(receipt));
  else console.info('[ENTRELUMEN_COOKING] ' + JSON.stringify(receipt));
});
