// Generated by tools/generate_family_balance.py --family pingpong5aero; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenPingpong5AeroSignature = "84c2ea8ad7272d0d56e1464124459c2721ce0c9424ff5b9e287a79d92d4b7425";
const entrelumenPingpong5AeroSources = {"create-aeronautics-bundled-1.21.1-1.3.2.jar":"a3f330d4757640f8715d991a43eedb826e4d0e51558d859c843ae6693bd35f1e"};
const entrelumenPingpong5AeroRows = [{"id":"simulated:physics_assembler","output":"simulated:physics_assembler","component":"entrelumen:handling_core","act":"III","json":{"type":"minecraft:crafting_shaped","category":"misc","key":{"A":{"item":"create:andesite_alloy"},"N":{"item":"minecraft:lever"},"R":{"item":"create:andesite_casing"},"Z":{"item":"entrelumen:handling_core"}},"pattern":[" Z "," N ","ARA"],"result":{"count":1,"id":"simulated:physics_assembler"}}}];
const entrelumenPingpong5AeroRemovals = [];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenPingpong5AeroRows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenPingpong5AeroRemovals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_PINGPONG5AERO_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenPingpong5AeroSignature, missing: missing}));
    throw new Error('ENTRELUMEN_PINGPONG5AERO_BALANCE preflight failed; native recipes were not changed');
  }
  entrelumenPingpong5AeroRows.forEach(row => {
    event.remove({id: row.id});
    event.custom(row.json).id(row.id);
  });
  entrelumenPingpong5AeroRemovals.forEach(id => event.remove({id: id}));
  console.info('[ENTRELUMEN_PINGPONG5AERO_BALANCE] ' + JSON.stringify({status: 'registered', signature: entrelumenPingpong5AeroSignature, changed: entrelumenPingpong5AeroRows.length,
    removed: entrelumenPingpong5AeroRemovals.length - absent.length, alreadyAbsent: absent}));
});
function entrelumenPingpong5AeroFieldCheck(event, row) {
  // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
  var found = 0;
  try {
    var stack = Item.of(row.component);
    event.forEachRecipe({id: row.id}, holder => {
      holder.value()[row.field].forEach(ingredient => { if (ingredient.test(stack)) found++; });
    });
  } catch (error) {
    console.warn('[ENTRELUMEN_PINGPONG5AERO_BALANCE] ' + JSON.stringify({status: 'field-check-error', recipe: row.id, error: String(error)}));
    return -1;
  }
  return found;
}
ServerEvents.afterRecipes(event => {
  var failed = [];
  entrelumenPingpong5AeroRows.forEach(row => {
    var loaded = event.countRecipes({id: row.id, output: row.output});
    var staged = event.countRecipes({id: row.id, input: row.component});
    if (staged === 0 && row.field) staged = entrelumenPingpong5AeroFieldCheck(event, row);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenPingpong5AeroRemovals.forEach(id => { var left = event.countRecipes({id: id}); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_PINGPONG5AERO_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenPingpong5AeroSignature, checked: entrelumenPingpong5AeroRows.length + entrelumenPingpong5AeroRemovals.length, failed: failed}));
});
