// Generated by tools/generate_family_balance.py --family neovitae; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenNeovitaeSignature = "783c1ade469293cd084276fce4626d6e0de6094822e515cabd1a977a8190b63a";
const entrelumenNeovitaeSources = {"neovitae-1.21.1-1.1.28.jar":"87cc61345d84e2f030f8caca47f66375d6d0e2dd63a3aa1095fa6ece4c3df5fe","sanguine_networks-1.21.1-2.0.jar":"7d4d97d1cb7af5cad0ce510dbee54323898046bfb523707ed5428adfd9a6d78b"};
const entrelumenNeovitaeRows = [{"id":"neovitae:ara_vitae","output":"neovitae:ara_vitae","component":"entrelumen:propagation_core","act":"III","json":{"type":"minecraft:crafting_shaped","category":"misc","key":{"f":{"item":"minecraft:furnace"},"g":{"tag":"c:ingots/gold"},"s":{"tag":"neovitae:vitae_stone"},"Z":{"item":"entrelumen:propagation_core"}},"pattern":["sZs","sfs","ggg"],"result":{"count":1,"id":"neovitae:ara_vitae"}}},{"id":"neovitae:ritual_stone_master","output":"neovitae:master_ritual_stone","component":"twilightforest:ironwood_ingot","act":"IV","json":{"type":"minecraft:crafting_shaped","category":"building","key":{"c":{"type":"neovitae:orb_tier","tier":2},"o":{"tag":"c:obsidians"},"s":{"item":"neovitae:ritual_stone"},"Z":{"item":"twilightforest:ironwood_ingot"}},"pattern":["ZsZ","scs","oso"],"result":{"count":1,"id":"neovitae:master_ritual_stone"}}},{"id":"sanguine_networks:virtual_sacrificer","output":"sanguine_networks:virtual_sacrificer","component":"twilightforest:ironwood_ingot","act":"IV","json":{"type":"minecraft:crafting_shaped","category":"misc","key":{"B":{"item":"neovitae:reagent_binding"},"C":{"item":"minecraft:comparator"},"D":{"item":"neovitae:rune_sacrifice"},"O":{"item":"minecraft:obsidian"},"S":{"item":"neovitae:tabula_animata"},"Z":{"item":"twilightforest:ironwood_ingot"}},"pattern":["ZDZ","SOS","BCB"],"result":{"count":1,"id":"sanguine_networks:virtual_sacrificer"}}}];
const entrelumenNeovitaeRemovals = ["neovitae:teleposer", "neovitae:ara_vitae/teleposer_focus", "neovitae:ara_vitae/enhanced_teleposer_focus", "neovitae:reinforced_teleposer_focus", "neovitae:alchemytable/reagent_teleposition", "neovitae:array/teleposition_sigil"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenNeovitaeRows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenNeovitaeRemovals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_NEOVITAE_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenNeovitaeSignature, missing: missing}));
    throw new Error('ENTRELUMEN_NEOVITAE_BALANCE preflight failed; native recipes were not changed');
  }
  entrelumenNeovitaeRows.forEach(row => {
    event.remove({id: row.id});
    event.custom(row.json).id(row.id);
  });
  entrelumenNeovitaeRemovals.forEach(id => event.remove({id: id}));
  console.info('[ENTRELUMEN_NEOVITAE_BALANCE] ' + JSON.stringify({status: 'registered', signature: entrelumenNeovitaeSignature, changed: entrelumenNeovitaeRows.length,
    removed: entrelumenNeovitaeRemovals.length - absent.length, alreadyAbsent: absent}));
});
function entrelumenNeovitaeFieldCheck(event, row) {
  // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
  var found = 0;
  try {
    var stack = Item.of(row.component);
    event.forEachRecipe({id: row.id}, holder => {
      holder.value()[row.field].forEach(ingredient => { if (ingredient.test(stack)) found++; });
    });
  } catch (error) {
    console.warn('[ENTRELUMEN_NEOVITAE_BALANCE] ' + JSON.stringify({status: 'field-check-error', recipe: row.id, error: String(error)}));
    return -1;
  }
  return found;
}
ServerEvents.afterRecipes(event => {
  var failed = [];
  entrelumenNeovitaeRows.forEach(row => {
    var loaded = event.countRecipes({id: row.id, output: row.output});
    var staged = event.countRecipes({id: row.id, input: row.component});
    if (staged === 0 && row.field) staged = entrelumenNeovitaeFieldCheck(event, row);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenNeovitaeRemovals.forEach(id => { var left = event.countRecipes({id: id}); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_NEOVITAE_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenNeovitaeSignature, checked: entrelumenNeovitaeRows.length + entrelumenNeovitaeRemovals.length, failed: failed}));
});
