// priority: 1000
// Generated by tools/generate_recipe_tools.py; edit that file, not this one.
// Shared helpers of the ENTRELUMEN recipe scripts. KubeJS runs every server script in one top-level scope and loads
// the higher priority first, so the other scripts call these from their events. Plain var and function on purpose:
// Rhino build.91 mishandles block-scoped const in repeated callbacks.

function entrelumenRecipeFailure(tag, signature, recipe, stage, error) {
  console.error('[' + tag + '] ' + JSON.stringify({status: 'failed-row', signature: signature, recipe: String(recipe),
    stage: stage, error: String(error)}));
}

// Replace (or add) one recipe. The replacement is built first and the native recipe is removed only if that worked:
// RecipesKubeEvent.custom throws for JSON it cannot read at all (no type, unknown type) and, for a type's own schema
// rejecting the fields (a Modern Industrialization machine, say), logs the error and returns a recipe it never
// registered (creationError). Either way the native recipe stays and the row reports `failed-row`.
function entrelumenCustomRecipe(event, tag, signature, id, json, removeNative) {
  var stage = 'build';
  var added = null;
  try {
    added = event.custom(json);
    if (!added || added.creationError === true) throw new Error('KubeJS rejected the recipe JSON (see the error above)');
    stage = 'id';
    added.id(id);
    if (removeNative) {
      stage = 'remove-native';
      event.remove({id: id});
    }
    return true;
  } catch (error) {
    entrelumenRecipeFailure(tag, signature, id, stage, error);
    if (added) {
      try { added.remove(); } catch (ignored) { /* the row is reported; nothing else to undo */ }
    }
    return false;
  }
}
function entrelumenReplaceRecipe(event, tag, signature, id, json) {
  return entrelumenCustomRecipe(event, tag, signature, id, json, true);
}
function entrelumenAddRecipe(event, tag, signature, id, json) {
  return entrelumenCustomRecipe(event, tag, signature, id, json, false);
}
function entrelumenRemoveRecipe(event, tag, signature, id) {
  try {
    event.remove({id: id});
    return true;
  } catch (error) {
    entrelumenRecipeFailure(tag, signature, id, 'remove', error);
    return false;
  }
}
