// Read-only: no recipe edits, inventory writes, progress or rewards.
// KubeJS 2101.7.2-build.374. API evidence: ../README.md.
// Generated by tools/check_runtime_content.py --sync; do not edit targets by hand.
const entrelumenAuditTargets = {
  "schema": 1,
  "items": [
    "actuallyadditions:palis_crystal",
    "actuallyadditions:restonia_crystal",
    "ae2:calculation_processor",
    "ae2:logic_processor",
    "aether:ambrosium_shard",
    "aether:zanite_gemstone",
    "amendments:dye_bottle",
    "aquaculture:fish_fillet_cooked",
    "ars_nouveau:magebloom_fiber",
    "buildinggadgets2:gadget_building",
    "chipped:botanist_workbench",
    "computercraft:computer_normal",
    "constructionstick:iron_stick",
    "cookingforblockheads:cooking_table",
    "create:andesite_alloy",
    "create:brass_sheet",
    "create:precision_mechanism",
    "entrelumen:atlas",
    "entrelumen:raw_lens",
    "entrelumen:signal_core",
    "entrelumen:survey_notes",
    "evilcraft:dark_gem",
    "farmersdelight:cutting_board",
    "farmersdelight:fish_stew",
    "farmersdelight:flint_knife",
    "farmersdelight:mixed_salad",
    "farmersdelight:vegetable_soup",
    "farmingforblockheads:market",
    "framedblocks:framed_cube",
    "functionalstorage:storage_controller",
    "handcrafted:oak_chair",
    "immersiveengineering:component_steel",
    "immersiveengineering:plate_steel",
    "immersiveengineering:wire_copper",
    "integrateddynamics:crystalized_menril_chunk",
    "integratedtunnels:part_interface_item",
    "laserio:logic_chip",
    "malum:arcane_spirit",
    "malum:soul_stained_steel_ingot",
    "mekanism:alloy_atomic",
    "mekanism:basic_control_circuit",
    "mekanismgenerators:wind_generator",
    "minecraft:book",
    "minecraft:bowl",
    "minecraft:bread",
    "minecraft:bucket",
    "minecraft:chest",
    "minecraft:compass",
    "minecraft:copper_ingot",
    "minecraft:crafting_table",
    "minecraft:furnace",
    "minecraft:glass",
    "minecraft:map",
    "minecraft:paper",
    "minecraft:red_bed",
    "minecraft:stone_pickaxe",
    "minecraft:torch",
    "minecraft:wheat",
    "modularrouters:blank_module",
    "mysticalagriculture:imperium_essence",
    "mysticalagriculture:prudentium_essence",
    "naturesaura:infused_iron",
    "naturesaura:sky_ingot",
    "occultism:iesnium_ingot",
    "occultism:spirit_attuned_crystal",
    "pipez:item_pipe",
    "pneumaticcraft:printed_circuit_board",
    "productivebees:wax",
    "rechiseled:chisel",
    "sophisticatedbackpacks:backpack",
    "sophisticatedstorage:barrel",
    "supplementaries:notice_board",
    "the_bumblezone:pollen_puff",
    "twilightforest:ironwood_ingot",
    "twilightforest:steeleaf_ingot",
    "waystones:waystone"
  ],
  "recipes": [
    {
      "id": "entrelumen:atlas",
      "output": "entrelumen:atlas"
    },
    {
      "id": "entrelumen:raw_lens",
      "output": "entrelumen:raw_lens"
    },
    {
      "id": "entrelumen:signal_core",
      "output": "entrelumen:signal_core"
    },
    {
      "id": "entrelumen:survey_notes",
      "output": "entrelumen:survey_notes"
    },
    {
      "id": "farmersdelight:cutting_board",
      "output": "farmersdelight:cutting_board"
    },
    {
      "id": "farmersdelight:flint_knife",
      "output": "farmersdelight:flint_knife"
    }
  ],
  "signature": "ac0bd983cccce5ab"
};

ServerEvents.afterRecipes(event => {
  const targets = entrelumenAuditTargets;
  const run = String(Date.now());
  let failures = 0;
  const emit = row => {
    row.run = run;
    row.signature = targets.signature;
    console.info('[ENTRELUMEN_AUDIT] ' + JSON.stringify(row));
  };
  emit({kind: 'begin', items: targets.items.length, recipes: targets.recipes.length});
  targets.items.forEach(id => {
    const exists = Item.exists(id);
    if (!exists) failures++;
    emit({kind: 'item', id: id, exists: exists});
  });
  targets.recipes.forEach(spec => {
    // Filter evaluates the loaded recipe, not the source JSON or a guessed result.
    const matches = event.countRecipes({id: spec.id, output: spec.output});
    const alternatives = [];
    event.forEachRecipe({output: spec.output}, recipe => {
      alternatives.push(String(recipe.getOrCreateId()));
    });
    alternatives.sort();
    if (matches !== 1) failures++;
    emit({kind: 'recipe', id: spec.id, output: spec.output, matches: matches,
      alternatives: alternatives.slice(0, 64), alternativesTotal: alternatives.length});
  });
  emit({kind: 'summary', items: targets.items.length, recipes: targets.recipes.length,
    failures: failures, status: failures === 0 ? 'PASS' : 'FAIL'});
});
