// Generated by tools/generate_family_balance.py --family loops; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenLoopsSignature = "8b49002e4a46c3bbb435e826b8ead63e12401aac601d01dc93c867fd8c6c03db";
const entrelumenLoopsSources = {"ImmersiveEngineering-1.21.1-12.4.2-194.jar":"45942985a4a4aebf265b8e22a0c54a96208637471f36f2532ff5d4911322debc","create-1.21.1-6.0.10.jar":"ef87fe5709f1ba1f5b8bb20a2925b5afb4669e178fd6d8bf10c167759eefe37a","functionalstorage-1.21.1-1.5.8.jar":"e3e7368c28a24e7de5b877988aa92cc94ca7417c8f60b7d28e7f584a94a51147","oritech-neoforge-1.21.1-1.2.11.jar":"3f19077a966b5b3e65cba8ba80f50378b6715aeb47f4749df7c1f35434cee776","utilitarian-1.21.1-0.19.2.jar":"c7090ef1e7259339a22d49a97125e1514c186f4e0174834da39df6987720db78"};
const entrelumenLoopsRows = [];
const entrelumenLoopsRemovals = ["oritech:assembler/blazerod", "immersiveengineering:metalpress/blaze_rod", "create:crushing/prismarine_crystals", "utilitarian:utility/ice", "utilitarian:utility/packed_ice", "functionalstorage:compacting/ice", "functionalstorage:compacting/packed_ice"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenLoopsRows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenLoopsRemovals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_LOOPS_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenLoopsSignature, missing: missing}));
    throw new Error('ENTRELUMEN_LOOPS_BALANCE preflight failed; native recipes were not changed');
  }
  // Row by row: the replacement is built first and the native recipe goes only if that worked (entrelumen_recipe_tools.js),
  // so a row KubeJS rejects leaves its native recipe alone and does not stop the rows after it.
  var failedRows = [];
  var failedRemovals = [];
  entrelumenLoopsRows.forEach(row => {
    if (!entrelumenReplaceRecipe(event, 'ENTRELUMEN_LOOPS_BALANCE', entrelumenLoopsSignature, row.id, row.json)) failedRows.push(row.id);
  });
  entrelumenLoopsRemovals.forEach(id => {
    if (!entrelumenRemoveRecipe(event, 'ENTRELUMEN_LOOPS_BALANCE', entrelumenLoopsSignature, id)) failedRemovals.push(id);
  });
  console.info('[ENTRELUMEN_LOOPS_BALANCE] ' + JSON.stringify({status: failedRows.length || failedRemovals.length ? 'registered-with-failed-rows' : 'registered',
    signature: entrelumenLoopsSignature, changed: entrelumenLoopsRows.length - failedRows.length,
    removed: entrelumenLoopsRemovals.length - failedRemovals.length - absent.length, alreadyAbsent: absent,
    failedRows: failedRows.concat(failedRemovals)}));
});
// The checks read one shared index of the loaded recipes (entrelumen_recipe_tools.js), not a scan per row.
entrelumenAfterRecipes('ENTRELUMEN_LOOPS_BALANCE', index => {
  var failed = [];
  entrelumenLoopsRows.forEach(row => {
    var loaded = index.countIdOutput(row.id, row.output);
    var staged = index.countIdInput(row.id, row.component);
    // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
    if (staged === 0 && row.field) staged = index.countField('ENTRELUMEN_LOOPS_BALANCE', row.id, row.field, row.component);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenLoopsRemovals.forEach(id => { var left = index.count(id); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_LOOPS_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenLoopsSignature, checked: entrelumenLoopsRows.length + entrelumenLoopsRemovals.length, failed: failed}));
});
