// Generated by tools/generate_family_balance.py --family pingpong7; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenPingpong7Signature = "30a7b3d31dc7f912245f48e7a37e0341209a867ecf99f3c62d6a90f8c37b6907";
const entrelumenPingpong7Sources = {"MysticalAgradditions-1.21.1-8.0.14.jar":"8f65713181cdb61f67637c49f7200f8fb5b8fef2aaf314c4da116d60077c9e46","me_beam_former-1.21.1-1.3.0.jar":"cfd96ad8ec16a8f3286cb8ad33252ead0379bb83ed910980474889022d76dcb3"};
const entrelumenPingpong7Rows = [{"id":"mysticalagradditions:insanium_block_combine","output":"mysticalagradditions:insanium_block","component":"entrelumen:luminosity_nature","act":"VI","json":{"type":"crafting_shaped","pattern":[" Z ","ECE"," E "],"key":{"E":{"item":"mysticalagriculture:supremium_block"},"C":{"item":"mysticalagriculture:master_infusion_crystal"},"Z":{"item":"entrelumen:luminosity_nature"}},"result":{"id":"mysticalagradditions:insanium_block"}}}];
const entrelumenPingpong7Removals = ["mysticalagradditions:insanium_essence", "me_beam_former:wireless_energy_tower"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenPingpong7Rows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenPingpong7Removals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenPingpong7Signature, missing: missing}));
    throw new Error('ENTRELUMEN_PINGPONG7_BALANCE preflight failed; native recipes were not changed');
  }
  // Row by row: the replacement is built first and the native recipe goes only if that worked (entrelumen_recipe_tools.js),
  // so a row KubeJS rejects leaves its native recipe alone and does not stop the rows after it.
  var failedRows = [];
  var failedRemovals = [];
  entrelumenPingpong7Rows.forEach(row => {
    if (!entrelumenReplaceRecipe(event, 'ENTRELUMEN_PINGPONG7_BALANCE', entrelumenPingpong7Signature, row.id, row.json)) failedRows.push(row.id);
  });
  entrelumenPingpong7Removals.forEach(id => {
    if (!entrelumenRemoveRecipe(event, 'ENTRELUMEN_PINGPONG7_BALANCE', entrelumenPingpong7Signature, id)) failedRemovals.push(id);
  });
  console.info('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: failedRows.length || failedRemovals.length ? 'registered-with-failed-rows' : 'registered',
    signature: entrelumenPingpong7Signature, changed: entrelumenPingpong7Rows.length - failedRows.length,
    removed: entrelumenPingpong7Removals.length - failedRemovals.length - absent.length, alreadyAbsent: absent,
    failedRows: failedRows.concat(failedRemovals)}));
});
// The checks read one shared index of the loaded recipes (entrelumen_recipe_tools.js), not a scan per row.
entrelumenAfterRecipes('ENTRELUMEN_PINGPONG7_BALANCE', index => {
  var failed = [];
  entrelumenPingpong7Rows.forEach(row => {
    var loaded = index.countIdOutput(row.id, row.output);
    var staged = index.countIdInput(row.id, row.component);
    // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
    if (staged === 0 && row.field) staged = index.countField('ENTRELUMEN_PINGPONG7_BALANCE', row.id, row.field, row.component);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenPingpong7Removals.forEach(id => { var left = index.count(id); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_PINGPONG7_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenPingpong7Signature, checked: entrelumenPingpong7Rows.length + entrelumenPingpong7Removals.length, failed: failed}));
});
