// Read-only: no recipe edits, inventory writes, progress or rewards.
// KubeJS 2101.7.2-build.374. API evidence: ../README.md.
// Generated by tools/check_runtime_content.py --sync; do not edit targets by hand.
const entrelumenAuditTargets = {
  "schema": 1,
  "items": [
    "actuallyadditions:atomic_reconstructor",
    "actuallyadditions:coal_generator",
    "actuallyadditions:iron_casing",
    "actuallyadditions:palis_crystal",
    "actuallyadditions:restonia_crystal",
    "ae2:calculation_processor",
    "ae2:logic_processor",
    "aether:ambrosium_shard",
    "aether:zanite_gemstone",
    "amendments:dye_bottle",
    "aquaculture:fish_fillet_cooked",
    "ars_nouveau:magebloom_fiber",
    "ars_nouveau:novice_spell_book",
    "ars_nouveau:source_gem",
    "buildinggadgets2:gadget_building",
    "chipped:botanist_workbench",
    "computercraft:computer_normal",
    "constructionstick:iron_stick",
    "cookingforblockheads:cooking_table",
    "create:andesite_alloy",
    "create:brass_sheet",
    "create:goggles",
    "create:iron_sheet",
    "create:mechanical_press",
    "create:precision_mechanism",
    "create:water_wheel",
    "entrelumen:arcane_module",
    "entrelumen:ark_bus",
    "entrelumen:ark_controller",
    "entrelumen:atlas",
    "entrelumen:calibration_frame",
    "entrelumen:containment_seal",
    "entrelumen:ecosystem_capsule",
    "entrelumen:energy_coupler",
    "entrelumen:engineering_module",
    "entrelumen:exploration_module",
    "entrelumen:growth_altar",
    "entrelumen:habitation_contract",
    "entrelumen:habitation_module",
    "entrelumen:handling_core",
    "entrelumen:horizon_chart",
    "entrelumen:inventory_sensor",
    "entrelumen:living_matrix",
    "entrelumen:logistics_module",
    "entrelumen:nature_module",
    "entrelumen:peace_altar",
    "entrelumen:power_regulator",
    "entrelumen:propagation_core",
    "entrelumen:ration_bundle",
    "entrelumen:raw_lens",
    "entrelumen:renewal_altar",
    "entrelumen:renewal_engine",
    "entrelumen:repose_altar",
    "entrelumen:routing_matrix",
    "entrelumen:signal_core",
    "entrelumen:spectral_lens",
    "entrelumen:survey_notes",
    "entrelumen:survey_station",
    "entrelumen:terraform_altar",
    "entrelumen:time_altar",
    "evilcraft:dark_gem",
    "farmersdelight:cooking_pot",
    "farmersdelight:cutting_board",
    "farmersdelight:fish_stew",
    "farmersdelight:flint_knife",
    "farmersdelight:mixed_salad",
    "farmersdelight:vegetable_soup",
    "farmingforblockheads:market",
    "framedblocks:framed_cube",
    "functionalstorage:storage_controller",
    "handcrafted:oak_chair",
    "immersiveengineering:component_steel",
    "immersiveengineering:plate_steel",
    "immersiveengineering:wire_copper",
    "integrateddynamics:crystalized_menril_chunk",
    "integratedtunnels:part_interface_item",
    "laserio:logic_chip",
    "malum:arcane_spirit",
    "malum:soul_stained_steel_ingot",
    "mekanism:alloy_atomic",
    "mekanism:basic_control_circuit",
    "mekanismgenerators:wind_generator",
    "minecraft:book",
    "minecraft:bowl",
    "minecraft:bread",
    "minecraft:bucket",
    "minecraft:chest",
    "minecraft:compass",
    "minecraft:copper_ingot",
    "minecraft:crafting_table",
    "minecraft:end_stone",
    "minecraft:ender_eye",
    "minecraft:filled_map",
    "minecraft:furnace",
    "minecraft:glass",
    "minecraft:hopper",
    "minecraft:lantern",
    "minecraft:map",
    "minecraft:paper",
    "minecraft:red_bed",
    "minecraft:redstone",
    "minecraft:stone_pickaxe",
    "minecraft:torch",
    "minecraft:wheat",
    "modularrouters:blank_module",
    "mysticalagriculture:imperium_essence",
    "mysticalagriculture:prudentium_essence",
    "naturesaura:infused_iron",
    "naturesaura:sky_ingot",
    "occultism:iesnium_ingot",
    "occultism:spirit_attuned_crystal",
    "pipez:item_pipe",
    "pneumaticcraft:printed_circuit_board",
    "productivebees:wax",
    "rechiseled:chisel",
    "sophisticatedbackpacks:backpack",
    "sophisticatedbackpacks:deposit_upgrade",
    "sophisticatedbackpacks:pickup_upgrade",
    "sophisticatedbackpacks:refill_upgrade",
    "sophisticatedstorage:barrel",
    "sophisticatedstorage:chest",
    "sophisticatedstorage:controller",
    "sophisticatedstorage:filter_upgrade",
    "supplementaries:notice_board",
    "the_bumblezone:pollen_puff",
    "twilightforest:ironwood_ingot",
    "twilightforest:steeleaf_ingot",
    "waystones:waystone"
  ],
  "recipes": [
    {
      "id": "entrelumen:ark_controller",
      "output": "entrelumen:ark_controller"
    },
    {
      "id": "entrelumen:atlas",
      "output": "entrelumen:atlas"
    },
    {
      "id": "entrelumen:growth_altar_duplication",
      "output": "entrelumen:growth_altar"
    },
    {
      "id": "entrelumen:integration/ark_arcana",
      "output": "entrelumen:arcane_module"
    },
    {
      "id": "entrelumen:integration/ark_engineering",
      "output": "entrelumen:engineering_module"
    },
    {
      "id": "entrelumen:integration/ark_exploration",
      "output": "entrelumen:exploration_module"
    },
    {
      "id": "entrelumen:integration/ark_habitation",
      "output": "entrelumen:habitation_module"
    },
    {
      "id": "entrelumen:integration/ark_logistics",
      "output": "entrelumen:logistics_module"
    },
    {
      "id": "entrelumen:integration/ark_nature",
      "output": "entrelumen:nature_module"
    },
    {
      "id": "entrelumen:integration/crystal_grid",
      "output": "entrelumen:energy_coupler"
    },
    {
      "id": "entrelumen:integration/distributed_power",
      "output": "entrelumen:power_regulator"
    },
    {
      "id": "entrelumen:integration/horizon_survey",
      "output": "entrelumen:horizon_chart"
    },
    {
      "id": "entrelumen:integration/living_workshop",
      "output": "entrelumen:living_matrix"
    },
    {
      "id": "entrelumen:integration/measured_logistics",
      "output": "entrelumen:inventory_sensor"
    },
    {
      "id": "entrelumen:integration/nursery_protocol",
      "output": "entrelumen:propagation_core"
    },
    {
      "id": "entrelumen:integration/pollinator_treaty",
      "output": "entrelumen:ecosystem_capsule"
    },
    {
      "id": "entrelumen:integration/precision_bench",
      "output": "entrelumen:calibration_frame"
    },
    {
      "id": "entrelumen:integration/renewal_engine",
      "output": "entrelumen:renewal_engine"
    },
    {
      "id": "entrelumen:integration/resilient_backbone",
      "output": "entrelumen:ark_bus"
    },
    {
      "id": "entrelumen:integration/sealed_memory",
      "output": "entrelumen:containment_seal"
    },
    {
      "id": "entrelumen:integration/settlement_supply",
      "output": "entrelumen:habitation_contract"
    },
    {
      "id": "entrelumen:integration/signal_exchange",
      "output": "entrelumen:routing_matrix"
    },
    {
      "id": "entrelumen:integration/spectral_archive",
      "output": "entrelumen:spectral_lens"
    },
    {
      "id": "entrelumen:integration/travelling_pantry",
      "output": "entrelumen:ration_bundle"
    },
    {
      "id": "entrelumen:integration/workshop_hands",
      "output": "entrelumen:handling_core"
    },
    {
      "id": "entrelumen:peace_altar_duplication",
      "output": "entrelumen:peace_altar"
    },
    {
      "id": "entrelumen:raw_lens",
      "output": "entrelumen:raw_lens"
    },
    {
      "id": "entrelumen:renewal_altar_duplication",
      "output": "entrelumen:renewal_altar"
    },
    {
      "id": "entrelumen:repose_altar_duplication",
      "output": "entrelumen:repose_altar"
    },
    {
      "id": "entrelumen:signal_core",
      "output": "entrelumen:signal_core"
    },
    {
      "id": "entrelumen:survey_notes",
      "output": "entrelumen:survey_notes"
    },
    {
      "id": "entrelumen:survey_station",
      "output": "entrelumen:survey_station"
    },
    {
      "id": "entrelumen:terraform_altar_duplication",
      "output": "entrelumen:terraform_altar"
    },
    {
      "id": "entrelumen:time_altar_duplication",
      "output": "entrelumen:time_altar"
    },
    {
      "id": "farmersdelight:cutting_board",
      "output": "farmersdelight:cutting_board"
    },
    {
      "id": "farmersdelight:flint_knife",
      "output": "farmersdelight:flint_knife"
    }
  ],
  "signature": "dcd9a1eef5973c5c"
};

ServerEvents.afterRecipes(event => {
  const targets = entrelumenAuditTargets;
  const run = String(Date.now());
  let failures = 0;
  const emit = row => {
    row.run = run;
    row.signature = targets.signature;
    console.info('[ENTRELUMEN_AUDIT] ' + JSON.stringify(row));
  };
  emit({kind: 'begin', items: targets.items.length, recipes: targets.recipes.length});
  targets.items.forEach(id => {
    const exists = Item.exists(id);
    if (!exists) failures++;
    emit({kind: 'item', id: id, exists: exists});
  });
  targets.recipes.forEach(spec => {
    // Filter evaluates the loaded recipe, not the source JSON or a guessed result.
    const matches = event.countRecipes({id: spec.id, output: spec.output});
    const alternatives = [];
    event.forEachRecipe({output: spec.output}, recipe => {
      alternatives.push(String(recipe.getOrCreateId()));
    });
    alternatives.sort();
    if (matches !== 1) failures++;
    emit({kind: 'recipe', id: spec.id, output: spec.output, matches: matches,
      alternatives: alternatives.slice(0, 64), alternativesTotal: alternatives.length});
  });
  emit({kind: 'summary', items: targets.items.length, recipes: targets.recipes.length,
    failures: failures, status: failures === 0 ? 'PASS' : 'FAIL'});
});
