// Generated by tools/generate_family_balance.py --family pingpong5compat; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenPingpong5CompatSignature = "b5965b22999f785c94343a8e099e965034288ba8aec1dcdb3349f5d1200923dd";
const entrelumenPingpong5CompatSources = {"AdvancedPeripherals-1.21.1-0.8.0a.jar":"5f1021046ba20a5c19ff56fbf5aaf9243355d9b8ccd9ae1b2777e8c5fb791b38"};
const entrelumenPingpong5CompatRows = [];
const entrelumenPingpong5CompatRemovals = ["advancedperipherals:ae_disk_cell_1m", "advancedperipherals:ae_disk_cell_4m", "advancedperipherals:ae_disk_cell_16m", "advancedperipherals:ae_disk_cell_64m", "advancedperipherals:ae_disk_cell_256m", "advancedperipherals:chunk_controller"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenPingpong5CompatRows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenPingpong5CompatRemovals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_PINGPONG5_COMPAT_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenPingpong5CompatSignature, missing: missing}));
    throw new Error('ENTRELUMEN_PINGPONG5_COMPAT_BALANCE preflight failed; native recipes were not changed');
  }
  // Row by row: the replacement is built first and the native recipe goes only if that worked (entrelumen_recipe_tools.js),
  // so a row KubeJS rejects leaves its native recipe alone and does not stop the rows after it.
  var failedRows = [];
  var failedRemovals = [];
  entrelumenPingpong5CompatRows.forEach(row => {
    if (!entrelumenReplaceRecipe(event, 'ENTRELUMEN_PINGPONG5_COMPAT_BALANCE', entrelumenPingpong5CompatSignature, row.id, row.json)) failedRows.push(row.id);
  });
  entrelumenPingpong5CompatRemovals.forEach(id => {
    if (!entrelumenRemoveRecipe(event, 'ENTRELUMEN_PINGPONG5_COMPAT_BALANCE', entrelumenPingpong5CompatSignature, id)) failedRemovals.push(id);
  });
  console.info('[ENTRELUMEN_PINGPONG5_COMPAT_BALANCE] ' + JSON.stringify({status: failedRows.length || failedRemovals.length ? 'registered-with-failed-rows' : 'registered',
    signature: entrelumenPingpong5CompatSignature, changed: entrelumenPingpong5CompatRows.length - failedRows.length,
    removed: entrelumenPingpong5CompatRemovals.length - failedRemovals.length - absent.length, alreadyAbsent: absent,
    failedRows: failedRows.concat(failedRemovals)}));
});
function entrelumenPingpong5CompatFieldCheck(event, row) {
  // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
  var found = 0;
  try {
    var stack = Item.of(row.component);
    event.forEachRecipe({id: row.id}, holder => {
      holder.value()[row.field].forEach(ingredient => { if (ingredient.test(stack)) found++; });
    });
  } catch (error) {
    console.warn('[ENTRELUMEN_PINGPONG5_COMPAT_BALANCE] ' + JSON.stringify({status: 'field-check-error', recipe: row.id, error: String(error)}));
    return -1;
  }
  return found;
}
ServerEvents.afterRecipes(event => {
  var failed = [];
  entrelumenPingpong5CompatRows.forEach(row => {
    var loaded = event.countRecipes({id: row.id, output: row.output});
    var staged = event.countRecipes({id: row.id, input: row.component});
    if (staged === 0 && row.field) staged = entrelumenPingpong5CompatFieldCheck(event, row);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenPingpong5CompatRemovals.forEach(id => { var left = event.countRecipes({id: id}); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_PINGPONG5_COMPAT_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenPingpong5CompatSignature, checked: entrelumenPingpong5CompatRows.length + entrelumenPingpong5CompatRemovals.length, failed: failed}));
});
