// Generated by tools/generate_family_balance.py --family boss_drops; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenBossDropsSignature = "961309770f1d518ad94e7c6c7655eaf2c10943b1bb02de951ab5d2daea2374fc";
const entrelumenBossDropsSources = {"rftoolsutility-1.21-7.0.12.jar":"1fdbf7505c6d6f4ef93b8b15961c9c1a6a4d35a5d676297f8f647916238f4d2a","theurgy-1.21.1-neoforge-1.76.0.jar":"c4bc955e30f1155b83954a0c2aba80adf19f72e6f5d95cfd8d72e5afb5e60d8f"};
const entrelumenBossDropsRows = [];
const entrelumenBossDropsRemovals = ["theurgy:incubation/nether_star", "theurgy:incubation/dragon_egg", "rftoolsutility:minecraft_wither", "rftoolsutility:minecraft_ender_dragon"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenBossDropsRows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenBossDropsRemovals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_BOSS_DROPS_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenBossDropsSignature, missing: missing}));
    throw new Error('ENTRELUMEN_BOSS_DROPS_BALANCE preflight failed; native recipes were not changed');
  }
  // Row by row: the replacement is built first and the native recipe goes only if that worked (entrelumen_recipe_tools.js),
  // so a row KubeJS rejects leaves its native recipe alone and does not stop the rows after it.
  var failedRows = [];
  var failedRemovals = [];
  entrelumenBossDropsRows.forEach(row => {
    if (!entrelumenReplaceRecipe(event, 'ENTRELUMEN_BOSS_DROPS_BALANCE', entrelumenBossDropsSignature, row.id, row.json)) failedRows.push(row.id);
  });
  entrelumenBossDropsRemovals.forEach(id => {
    if (!entrelumenRemoveRecipe(event, 'ENTRELUMEN_BOSS_DROPS_BALANCE', entrelumenBossDropsSignature, id)) failedRemovals.push(id);
  });
  console.info('[ENTRELUMEN_BOSS_DROPS_BALANCE] ' + JSON.stringify({status: failedRows.length || failedRemovals.length ? 'registered-with-failed-rows' : 'registered',
    signature: entrelumenBossDropsSignature, changed: entrelumenBossDropsRows.length - failedRows.length,
    removed: entrelumenBossDropsRemovals.length - failedRemovals.length - absent.length, alreadyAbsent: absent,
    failedRows: failedRows.concat(failedRemovals)}));
});
function entrelumenBossDropsFieldCheck(event, row) {
  // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
  var found = 0;
  try {
    var stack = Item.of(row.component);
    event.forEachRecipe({id: row.id}, holder => {
      holder.value()[row.field].forEach(ingredient => { if (ingredient.test(stack)) found++; });
    });
  } catch (error) {
    console.warn('[ENTRELUMEN_BOSS_DROPS_BALANCE] ' + JSON.stringify({status: 'field-check-error', recipe: row.id, error: String(error)}));
    return -1;
  }
  return found;
}
ServerEvents.afterRecipes(event => {
  var failed = [];
  entrelumenBossDropsRows.forEach(row => {
    var loaded = event.countRecipes({id: row.id, output: row.output});
    var staged = event.countRecipes({id: row.id, input: row.component});
    if (staged === 0 && row.field) staged = entrelumenBossDropsFieldCheck(event, row);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenBossDropsRemovals.forEach(id => { var left = event.countRecipes({id: id}); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_BOSS_DROPS_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenBossDropsSignature, checked: entrelumenBossDropsRows.length + entrelumenBossDropsRemovals.length, failed: failed}));
});
