// Generated by tools/generate_integration_recipes.py --write; do not edit.
// Static native recipes (15 shaped and symmetric, the frame by Mekanism infusion); no team, act, gifts, reward or inventory handlers.
const entrelumenIntegrationSignature = "c87f5c9ed651231ebe00596342df99e82c56ea1ef80eb19997d150fb51485d3c";
const entrelumenIntegrationRecipes = [
  {
    "id": "entrelumen:integration/precision_bench",
    "json": {
      "type": "mekanism:metallurgic_infusing",
      "chemical_input": {
        "amount": 40,
        "tag": "mekanism:redstone"
      },
      "item_input": {
        "count": 1,
        "item": "entrelumen:raw_lens"
      },
      "output": {
        "count": 1,
        "id": "entrelumen:calibration_frame"
      },
      "per_tick_usage": false
    }
  },
  {
    "id": "entrelumen:integration/crystal_grid",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "R R",
        " C ",
        "A A"
      ],
      "key": {
        "R": {
          "item": "actuallyadditions:restonia_crystal"
        },
        "C": {
          "item": "actuallyadditions:iron_casing"
        },
        "A": {
          "item": "create:andesite_alloy"
        }
      },
      "result": {
        "id": "entrelumen:energy_coupler",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/living_workshop",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " S ",
        "FMF",
        " S "
      ],
      "key": {
        "S": {
          "item": "ars_nouveau:source_gem"
        },
        "F": {
          "item": "ars_nouveau:magebloom_fiber"
        },
        "M": {
          "item": "entrelumen:calibration_frame"
        }
      },
      "result": {
        "id": "entrelumen:living_matrix",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/travelling_pantry",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " V ",
        "F F",
        " V "
      ],
      "key": {
        "V": {
          "item": "farmersdelight:vegetable_soup"
        },
        "F": {
          "item": "aquaculture:fish_fillet_cooked"
        }
      },
      "result": {
        "id": "entrelumen:ration_bundle",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/signal_exchange",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " P ",
        "LML",
        "A A"
      ],
      "key": {
        "P": {
          "item": "pneumaticcraft:printed_circuit_board"
        },
        "L": {
          "item": "ae2:logic_processor"
        },
        "M": {
          "item": "entrelumen:calibration_frame"
        },
        "A": {
          "item": "actuallyadditions:palis_crystal"
        }
      },
      "result": {
        "id": "entrelumen:routing_matrix",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/nursery_protocol",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "E E",
        " M ",
        "W W"
      ],
      "key": {
        "E": {
          "item": "mysticalagriculture:prudentium_essence"
        },
        "M": {
          "item": "entrelumen:living_matrix"
        },
        "W": {
          "item": "productivebees:wax"
        }
      },
      "result": {
        "id": "entrelumen:propagation_core",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/distributed_power",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " C ",
        "PKP",
        " C "
      ],
      "key": {
        "C": {
          "item": "mekanism:basic_control_circuit"
        },
        "P": {
          "item": "immersiveengineering:plate_steel"
        },
        "K": {
          "item": "entrelumen:energy_coupler"
        }
      },
      "result": {
        "id": "entrelumen:power_regulator",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/measured_logistics",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " N ",
        "LML",
        " N "
      ],
      "key": {
        "N": {
          "item": "integrateddynamics:crystalized_menril_chunk"
        },
        "L": {
          "item": "laserio:logic_chip"
        },
        "M": {
          "item": "entrelumen:routing_matrix"
        }
      },
      "result": {
        "id": "entrelumen:inventory_sensor",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/workshop_hands",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " P ",
        "BRB"
      ],
      "key": {
        "P": {
          "item": "create:precision_mechanism"
        },
        "B": {
          "item": "modularrouters:blank_module"
        },
        "R": {
          "item": "entrelumen:power_regulator"
        }
      },
      "result": {
        "id": "entrelumen:handling_core",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/spectral_archive",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " C ",
        "SMS",
        " P "
      ],
      "key": {
        "C": {
          "item": "occultism:spirit_attuned_crystal"
        },
        "S": {
          "item": "malum:arcane_spirit"
        },
        "M": {
          "item": "entrelumen:calibration_frame"
        },
        "P": {
          "item": "create:precision_mechanism"
        }
      },
      "result": {
        "id": "entrelumen:spectral_lens",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/horizon_survey",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "A A",
        "INI",
        " R "
      ],
      "key": {
        "A": {
          "item": "aether:ambrosium_shard"
        },
        "I": {
          "item": "twilightforest:ironwood_ingot"
        },
        "N": {
          "item": "entrelumen:survey_notes"
        },
        "R": {
          "item": "entrelumen:ration_bundle"
        }
      },
      "result": {
        "id": "entrelumen:horizon_chart",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/pollinator_treaty",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        " M ",
        "W W",
        "PMP"
      ],
      "key": {
        "M": {
          "item": "entrelumen:living_matrix"
        },
        "W": {
          "item": "productivebees:wax"
        },
        "P": {
          "item": "the_bumblezone:pollen_puff"
        }
      },
      "result": {
        "id": "entrelumen:ecosystem_capsule",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/sealed_memory",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "D D",
        " L ",
        "S S"
      ],
      "key": {
        "D": {
          "item": "evilcraft:dark_gem"
        },
        "L": {
          "item": "entrelumen:spectral_lens"
        },
        "S": {
          "item": "malum:soul_stained_steel_ingot"
        }
      },
      "result": {
        "id": "entrelumen:containment_seal",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/resilient_backbone",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "AHA",
        "PSP",
        " H "
      ],
      "key": {
        "A": {
          "item": "mekanism:alloy_atomic"
        },
        "H": {
          "item": "entrelumen:handling_core"
        },
        "P": {
          "item": "pneumaticcraft:printed_circuit_board"
        },
        "S": {
          "item": "entrelumen:inventory_sensor"
        }
      },
      "result": {
        "id": "entrelumen:ark_bus",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/renewal_engine",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "KCK",
        "I I",
        "PCP"
      ],
      "key": {
        "K": {
          "item": "naturesaura:sky_ingot"
        },
        "C": {
          "item": "entrelumen:ecosystem_capsule"
        },
        "I": {
          "item": "mysticalagriculture:imperium_essence"
        },
        "P": {
          "item": "entrelumen:propagation_core"
        }
      },
      "result": {
        "id": "entrelumen:renewal_engine",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/settlement_supply",
    "json": {
      "type": "minecraft:crafting_shaped",
      "category": "misc",
      "pattern": [
        "FRF",
        "SCS",
        " R "
      ],
      "key": {
        "F": {
          "item": "farmersdelight:fish_stew"
        },
        "R": {
          "item": "entrelumen:ration_bundle"
        },
        "S": {
          "item": "farmersdelight:mixed_salad"
        },
        "C": {
          "item": "ae2:calculation_processor"
        }
      },
      "result": {
        "id": "entrelumen:habitation_contract",
        "count": 1
      }
    }
  }
];

// Shaped rows name their result and key; the infusing row its output and item input.
function entrelumenIntegrationOutput(row) {
  return row.json.result ? row.json.result.id : row.json.output.id;
}
ServerEvents.recipes(event => {
  const errors = [];
  entrelumenIntegrationRecipes.forEach(row => {
    const inputs = row.json.key ? Object.keys(row.json.key).map(k => row.json.key[k].item) : [row.json.item_input.item];
    const ids = [entrelumenIntegrationOutput(row)].concat(inputs);
    ids.forEach(id => {
      if (!Item.exists(id)) errors.push({recipe: row.id, missingItem: id});
    });
    if (event.containsRecipe({id: row.id})) errors.push({recipe: row.id, collision: true});
  });
  if (errors.length) {
    console.error('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenIntegrationSignature, added: 0, errors: errors}));
    throw new Error('ENTRELUMEN integration recipes preflight failed; see contextual errors. No integration recipes were added.');
  }
  entrelumenIntegrationRecipes.forEach(row => event.custom(row.json).id(row.id));
  console.info('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify({status: 'registered', signature: entrelumenIntegrationSignature, recipes: entrelumenIntegrationRecipes.length}));
});

ServerEvents.afterRecipes(event => {
  const missing = [];
  entrelumenIntegrationRecipes.forEach(row => {
    if (event.countRecipes({id: row.id, output: entrelumenIntegrationOutput(row)}) !== 1) missing.push(row.id);
  });
  const receipt = {status: missing.length ? 'failed-loaded-check' : 'loaded', signature: entrelumenIntegrationSignature, checked: entrelumenIntegrationRecipes.length, missing: missing};
  if (missing.length) console.error('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify(receipt));
  else console.info('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify(receipt));
});
