// Generated by tools/generate_integration_recipes.py --write; do not edit.
// Static native recipes; no team, act, gifts, reward or inventory handlers.
const entrelumenIntegrationSignature = "cdbfbbe6c1e29a628d25830318f64689cc21214b799eed0c0a125642e0be78dc";
const entrelumenIntegrationRecipes = [
  {
    "id": "entrelumen:integration/precision_bench",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "create:iron_sheet"
        },
        {
          "item": "create:iron_sheet"
        },
        {
          "item": "immersiveengineering:wire_copper"
        },
        {
          "item": "immersiveengineering:wire_copper"
        },
        {
          "item": "entrelumen:raw_lens"
        }
      ],
      "result": {
        "id": "entrelumen:calibration_frame",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/crystal_grid",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "actuallyadditions:restonia_crystal"
        },
        {
          "item": "actuallyadditions:restonia_crystal"
        },
        {
          "item": "actuallyadditions:iron_casing"
        },
        {
          "item": "create:andesite_alloy"
        },
        {
          "item": "create:andesite_alloy"
        }
      ],
      "result": {
        "id": "entrelumen:energy_coupler",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/living_workshop",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "ars_nouveau:magebloom_fiber"
        },
        {
          "item": "ars_nouveau:magebloom_fiber"
        },
        {
          "item": "ars_nouveau:source_gem"
        },
        {
          "item": "ars_nouveau:source_gem"
        },
        {
          "item": "entrelumen:calibration_frame"
        }
      ],
      "result": {
        "id": "entrelumen:living_matrix",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/travelling_pantry",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "farmersdelight:vegetable_soup"
        },
        {
          "item": "farmersdelight:vegetable_soup"
        },
        {
          "item": "aquaculture:fish_fillet_cooked"
        },
        {
          "item": "aquaculture:fish_fillet_cooked"
        }
      ],
      "result": {
        "id": "entrelumen:ration_bundle",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/signal_exchange",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "ae2:logic_processor"
        },
        {
          "item": "ae2:logic_processor"
        },
        {
          "item": "pneumaticcraft:printed_circuit_board"
        },
        {
          "item": "actuallyadditions:palis_crystal"
        },
        {
          "item": "actuallyadditions:palis_crystal"
        },
        {
          "item": "entrelumen:calibration_frame"
        }
      ],
      "result": {
        "id": "entrelumen:routing_matrix",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/nursery_protocol",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "mysticalagriculture:prudentium_essence"
        },
        {
          "item": "mysticalagriculture:prudentium_essence"
        },
        {
          "item": "productivebees:wax"
        },
        {
          "item": "productivebees:wax"
        },
        {
          "item": "entrelumen:living_matrix"
        }
      ],
      "result": {
        "id": "entrelumen:propagation_core",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/distributed_power",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "mekanism:basic_control_circuit"
        },
        {
          "item": "mekanism:basic_control_circuit"
        },
        {
          "item": "immersiveengineering:plate_steel"
        },
        {
          "item": "immersiveengineering:plate_steel"
        },
        {
          "item": "entrelumen:energy_coupler"
        }
      ],
      "result": {
        "id": "entrelumen:power_regulator",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/measured_logistics",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "integrateddynamics:crystalized_menril_chunk"
        },
        {
          "item": "integrateddynamics:crystalized_menril_chunk"
        },
        {
          "item": "laserio:logic_chip"
        },
        {
          "item": "laserio:logic_chip"
        },
        {
          "item": "entrelumen:routing_matrix"
        }
      ],
      "result": {
        "id": "entrelumen:inventory_sensor",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/workshop_hands",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "modularrouters:blank_module"
        },
        {
          "item": "modularrouters:blank_module"
        },
        {
          "item": "create:precision_mechanism"
        },
        {
          "item": "entrelumen:power_regulator"
        }
      ],
      "result": {
        "id": "entrelumen:handling_core",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/spectral_archive",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "occultism:spirit_attuned_crystal"
        },
        {
          "item": "malum:arcane_spirit"
        },
        {
          "item": "malum:arcane_spirit"
        },
        {
          "item": "create:precision_mechanism"
        },
        {
          "item": "entrelumen:calibration_frame"
        }
      ],
      "result": {
        "id": "entrelumen:spectral_lens",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/horizon_survey",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "aether:ambrosium_shard"
        },
        {
          "item": "aether:ambrosium_shard"
        },
        {
          "item": "twilightforest:ironwood_ingot"
        },
        {
          "item": "twilightforest:ironwood_ingot"
        },
        {
          "item": "entrelumen:survey_notes"
        },
        {
          "item": "entrelumen:ration_bundle"
        }
      ],
      "result": {
        "id": "entrelumen:horizon_chart",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/pollinator_treaty",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "the_bumblezone:pollen_puff"
        },
        {
          "item": "the_bumblezone:pollen_puff"
        },
        {
          "item": "productivebees:wax"
        },
        {
          "item": "productivebees:wax"
        },
        {
          "item": "entrelumen:living_matrix"
        },
        {
          "item": "entrelumen:living_matrix"
        }
      ],
      "result": {
        "id": "entrelumen:ecosystem_capsule",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/sealed_memory",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "evilcraft:dark_gem"
        },
        {
          "item": "evilcraft:dark_gem"
        },
        {
          "item": "malum:soul_stained_steel_ingot"
        },
        {
          "item": "malum:soul_stained_steel_ingot"
        },
        {
          "item": "entrelumen:spectral_lens"
        }
      ],
      "result": {
        "id": "entrelumen:containment_seal",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/resilient_backbone",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "mekanism:alloy_atomic"
        },
        {
          "item": "mekanism:alloy_atomic"
        },
        {
          "item": "pneumaticcraft:printed_circuit_board"
        },
        {
          "item": "pneumaticcraft:printed_circuit_board"
        },
        {
          "item": "entrelumen:handling_core"
        },
        {
          "item": "entrelumen:handling_core"
        },
        {
          "item": "entrelumen:inventory_sensor"
        }
      ],
      "result": {
        "id": "entrelumen:ark_bus",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/renewal_engine",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "naturesaura:sky_ingot"
        },
        {
          "item": "naturesaura:sky_ingot"
        },
        {
          "item": "mysticalagriculture:imperium_essence"
        },
        {
          "item": "mysticalagriculture:imperium_essence"
        },
        {
          "item": "entrelumen:ecosystem_capsule"
        },
        {
          "item": "entrelumen:ecosystem_capsule"
        },
        {
          "item": "entrelumen:propagation_core"
        },
        {
          "item": "entrelumen:propagation_core"
        }
      ],
      "result": {
        "id": "entrelumen:renewal_engine",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/settlement_supply",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "farmersdelight:fish_stew"
        },
        {
          "item": "farmersdelight:fish_stew"
        },
        {
          "item": "farmersdelight:mixed_salad"
        },
        {
          "item": "farmersdelight:mixed_salad"
        },
        {
          "item": "ae2:calculation_processor"
        },
        {
          "item": "entrelumen:ration_bundle"
        },
        {
          "item": "entrelumen:ration_bundle"
        }
      ],
      "result": {
        "id": "entrelumen:habitation_contract",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/ark_engineering",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "entrelumen:calibration_frame"
        },
        {
          "item": "entrelumen:calibration_frame"
        },
        {
          "item": "entrelumen:energy_coupler"
        },
        {
          "item": "entrelumen:energy_coupler"
        },
        {
          "item": "entrelumen:ark_bus"
        },
        {
          "item": "mekanism:alloy_atomic"
        },
        {
          "item": "mekanism:alloy_atomic"
        }
      ],
      "result": {
        "id": "entrelumen:engineering_module",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/ark_arcana",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "entrelumen:spectral_lens"
        },
        {
          "item": "entrelumen:spectral_lens"
        },
        {
          "item": "entrelumen:containment_seal"
        },
        {
          "item": "entrelumen:containment_seal"
        },
        {
          "item": "occultism:iesnium_ingot"
        },
        {
          "item": "occultism:iesnium_ingot"
        }
      ],
      "result": {
        "id": "entrelumen:arcane_module",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/ark_nature",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "entrelumen:renewal_engine"
        },
        {
          "item": "entrelumen:ecosystem_capsule"
        },
        {
          "item": "entrelumen:ecosystem_capsule"
        },
        {
          "item": "entrelumen:living_matrix"
        },
        {
          "item": "entrelumen:living_matrix"
        }
      ],
      "result": {
        "id": "entrelumen:nature_module",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/ark_exploration",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "entrelumen:horizon_chart"
        },
        {
          "item": "entrelumen:spectral_lens"
        },
        {
          "item": "twilightforest:steeleaf_ingot"
        },
        {
          "item": "twilightforest:steeleaf_ingot"
        },
        {
          "item": "aether:zanite_gemstone"
        },
        {
          "item": "aether:zanite_gemstone"
        }
      ],
      "result": {
        "id": "entrelumen:exploration_module",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/ark_logistics",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "entrelumen:routing_matrix"
        },
        {
          "item": "entrelumen:routing_matrix"
        },
        {
          "item": "entrelumen:handling_core"
        },
        {
          "item": "entrelumen:handling_core"
        },
        {
          "item": "entrelumen:ark_bus"
        }
      ],
      "result": {
        "id": "entrelumen:logistics_module",
        "count": 1
      }
    }
  },
  {
    "id": "entrelumen:integration/ark_habitation",
    "json": {
      "type": "minecraft:crafting_shapeless",
      "category": "misc",
      "ingredients": [
        {
          "item": "entrelumen:habitation_contract"
        },
        {
          "item": "entrelumen:ration_bundle"
        },
        {
          "item": "entrelumen:ration_bundle"
        },
        {
          "item": "entrelumen:living_matrix"
        },
        {
          "item": "entrelumen:living_matrix"
        }
      ],
      "result": {
        "id": "entrelumen:habitation_module",
        "count": 1
      }
    }
  }
];

ServerEvents.recipes(event => {
  const errors = [];
  entrelumenIntegrationRecipes.forEach(row => {
    const ids = [row.json.result.id].concat(row.json.ingredients.map(i => i.item));
    ids.forEach(id => {
      if (!Item.exists(id)) errors.push({recipe: row.id, missingItem: id});
    });
    if (event.containsRecipe({id: row.id})) errors.push({recipe: row.id, collision: true});
  });
  if (errors.length) {
    console.error('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenIntegrationSignature, added: 0, errors: errors}));
    throw new Error('ENTRELUMEN integration recipes preflight failed; see contextual errors. No integration recipes were added.');
  }
  entrelumenIntegrationRecipes.forEach(row => event.custom(row.json).id(row.id));
  console.info('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify({status: 'registered', signature: entrelumenIntegrationSignature, recipes: entrelumenIntegrationRecipes.length}));
});

ServerEvents.afterRecipes(event => {
  const missing = [];
  entrelumenIntegrationRecipes.forEach(row => {
    if (event.countRecipes({id: row.id, output: row.json.result.id}) !== 1) missing.push(row.id);
  });
  const receipt = {status: missing.length ? 'failed-loaded-check' : 'loaded', signature: entrelumenIntegrationSignature, checked: entrelumenIntegrationRecipes.length, missing: missing};
  if (missing.length) console.error('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify(receipt));
  else console.info('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify(receipt));
});
