// Generated by tools/generate_jetpack_balance.py from content/jetpack-balance.json; edit those, not this file.
// ENTRELUMEN jetpack balance (Elias, 25 September 2026): every jetpack pays 2.5 times its native energy per
// tick. Iron Jetpacks, Oritech and the PneumaticCraft Jet Boots read it from pack/config. The pieces below fix their
// per-tick cost in code, so after each player tick this script takes 1.5 times what the worn chest piece lost
// since the previous tick, once the mod has taken its own share. A loss above the piece's native maximum per tick is a
// swap, not flight, and is not charged; a tick in which something also charged the piece is not charged either.
const entrelumenJetpackSurcharge = {
  "mekanism:jetpack": {"kind": "chemical", "max": 1},
  "mekanism:jetpack_armored": {"kind": "chemical", "max": 1},
  "mekanism:mekasuit_bodyarmor": {"kind": "chemical", "max": 4},
  "modern_industrialization:diesel_jetpack": {"kind": "fluid", "max": 2},
  "ad_astra:jet_suit": {"kind": "energy", "max": 100}
};
const entrelumenJetpackExtra = 1.5;
const entrelumenJetpackSeen = {};
var entrelumenJetpackApi = null;
var entrelumenJetpackBroken = false;

function entrelumenJetpackLoad() {
  if (entrelumenJetpackApi !== null) return entrelumenJetpackApi;
  var api = {};
  api.chest = Java.loadClass('net.minecraft.world.entity.EquipmentSlot').CHEST;
  api.items = Java.loadClass('net.minecraft.core.registries.BuiltInRegistries').ITEM;
  api.energy = Java.loadClass('net.neoforged.neoforge.capabilities.Capabilities$EnergyStorage').ITEM;
  api.fluid = Java.loadClass('net.neoforged.neoforge.capabilities.Capabilities$FluidHandler').ITEM;
  api.fluidExecute = Java.loadClass('net.neoforged.neoforge.fluids.capability.IFluidHandler$FluidAction').EXECUTE;
  api.chemical = null;
  if (Platform.isLoaded('mekanism')) {
    api.chemical = Java.loadClass('mekanism.common.capabilities.Capabilities').CHEMICAL.item();
    api.chemicalExecute = Java.loadClass('mekanism.api.Action').EXECUTE;
  }
  entrelumenJetpackApi = api;
  return api;
}

// What the worn piece holds of its fuel (energy, fluid or hydrogen) and how to take some of it; null if it has no store.
function entrelumenJetpackStore(api, stack, kind) {
  if (kind === 'energy') {
    var energy = stack.getCapability(api.energy);
    if (energy === null) return null;
    return {amount: Number(energy.getEnergyStored()), take: n => Number(energy.extractEnergy(n, false))};
  }
  if (kind === 'fluid') {
    var fluid = stack.getCapability(api.fluid);
    if (fluid === null || fluid.getTanks() < 1) return null;
    return {amount: Number(fluid.getFluidInTank(0).getAmount()),
      take: n => Number(fluid.drain(n, api.fluidExecute).getAmount())};
  }
  if (kind === 'chemical' && api.chemical !== null) {
    var chemical = stack.getCapability(api.chemical);
    if (chemical === null) return null;
    var tanks = [];
    var total = 0;
    for (var tank = 0; tank < chemical.getChemicalTanks(); tank++) {
      var held = chemical.getChemicalInTank(tank);
      if (held.isEmpty() || String(held.getTypeRegistryName()) !== 'mekanism:hydrogen') continue;
      tanks.push(tank);
      total += Number(held.getAmount());
    }
    return {amount: total, take: n => {
      var taken = 0;
      tanks.forEach(index => {
        if (taken < n) taken += Number(chemical.extractChemical(index, n - taken, api.chemicalExecute).getAmount());
      });
      return taken;
    }};
  }
  return null;
}

// seen is what the same player wore on the previous tick ({id, amount, carry}) or undefined.
// Returns [whole units to take now, the fraction carried to the next tick].
function entrelumenJetpackCharge(seen, id, amount, max) {
  if (!seen || seen.id !== id) return [0, 0];
  var lost = seen.amount - amount;
  if (lost <= 0 || lost > max) return [0, seen.carry];
  var owed = seen.carry + lost * entrelumenJetpackExtra;
  var whole = Math.floor(owed);
  return [whole, owed - whole];
}

PlayerEvents.tick(event => {
  if (entrelumenJetpackBroken) return;
  var key = String(event.player.getStringUUID());
  try {
    var api = entrelumenJetpackLoad();
    var stack = event.player.getItemBySlot(api.chest);
    var id = stack.isEmpty() ? '' : String(api.items.getKey(stack.getItem()));
    var spec = entrelumenJetpackSurcharge[id];
    var store = spec ? entrelumenJetpackStore(api, stack, spec.kind) : null;
    if (store === null) {
      delete entrelumenJetpackSeen[key];
      return;
    }
    var charge = entrelumenJetpackCharge(entrelumenJetpackSeen[key], id, store.amount, spec.max);
    var amount = store.amount;
    if (charge[0] > 0) amount -= store.take(charge[0]);
    entrelumenJetpackSeen[key] = {id: id, amount: amount, carry: charge[1]};
  } catch (error) {
    // One report, then the surcharge stays off until the next reload instead of failing every tick.
    entrelumenJetpackBroken = true;
    console.error('ENTRELUMEN jetpack surcharge disabled: ' + error);
  }
});

PlayerEvents.loggedOut(event => {
  delete entrelumenJetpackSeen[String(event.player.getStringUUID())];
});
