// Generated by tools/generate_family_balance.py --family arcane; native acquisition only.
// No team, act, use, dimension, origin, gift or reward checks.
const entrelumenArcaneSignature = "00274e493bc277527dd3df27bc80464887039dd2525b5bad0210f30e561a3498";
const entrelumenArcaneSources = {"reliquary-1.21.1-2.0.80.1570.jar":"9db4976657e7e8898c866836f9fbb40dc54239a5432463a5aeafc08264aac453","theurgy-1.21.1-neoforge-1.76.0.jar":"c4bc955e30f1155b83954a0c2aba80adf19f72e6f5d95cfd8d72e5afb5e60d8f"};
const entrelumenArcaneRows = [{"id":"reliquary:rending_gale","output":"reliquary:rending_gale","component":"aether:zanite_gemstone","act":"IV","json":{"type":"minecraft:crafting_shaped","category":"misc","key":{"B":{"item":"reliquary:bat_wing"},"E":{"item":"reliquary:eye_of_the_storm"},"G":{"tag":"c:ingots/gold"},"S":{"item":"minecraft:stick"},"V":{"type":"neoforge:components","components":{"minecraft:attribute_modifiers":{"modifiers":[]},"minecraft:enchantments":{"levels":{}},"minecraft:lore":[],"minecraft:max_stack_size":64,"minecraft:rarity":"common","minecraft:repair_cost":0},"items":"reliquary:void_tear","strict":true},"Z":{"item":"aether:zanite_gemstone"}},"pattern":[" BE","ZVB","SG "],"result":{"count":1,"id":"reliquary:rending_gale"}}},{"id":"theurgy:crafting/shaped/sulfuric_flux_emitter","output":"theurgy:sulfuric_flux_emitter","component":"entrelumen:containment_seal","act":"IV","json":{"type":"minecraft:crafting_shaped","category":"misc","key":{"S":{"tag":"theurgy:alchemical_sulfurs"},"a":{"tag":"c:gems/sal_ammoniac"},"g":{"tag":"c:ingots/gold"},"s":{"tag":"c:stones"},"Z":{"item":"entrelumen:containment_seal"}},"pattern":[" a ","gSg","sZs"],"result":{"count":1,"id":"theurgy:sulfuric_flux_emitter"}}}];
const entrelumenArcaneRemovals = ["reliquary:alkahestry_tome", "reliquary:uncrafting/spawn_egg", "reliquary:alkahestry/crafting/charcoal", "reliquary:alkahestry/crafting/clay", "reliquary:alkahestry/crafting/copper_ingot", "reliquary:alkahestry/crafting/diamond", "reliquary:alkahestry/crafting/dirt", "reliquary:alkahestry/crafting/emerald", "reliquary:alkahestry/crafting/end_stone", "reliquary:alkahestry/crafting/flint", "reliquary:alkahestry/crafting/gold_ingot", "reliquary:alkahestry/crafting/gravel", "reliquary:alkahestry/crafting/gunpowder", "reliquary:alkahestry/crafting/iron_ingot", "reliquary:alkahestry/crafting/lapis_lazuli", "reliquary:alkahestry/crafting/nether_star", "reliquary:alkahestry/crafting/netherrack", "reliquary:alkahestry/crafting/obsidian", "reliquary:alkahestry/crafting/sand", "reliquary:alkahestry/crafting/sandstone", "reliquary:alkahestry/crafting/silver_ingot", "reliquary:alkahestry/crafting/soul_sand", "reliquary:alkahestry/crafting/steel_ingot", "reliquary:alkahestry/crafting/tin_ingot"];

ServerEvents.recipes(event => {
  var missing = [];
  entrelumenArcaneRows.forEach(row => {
    if (!event.containsRecipe({id: row.id})) missing.push({recipe: row.id, cause: 'native recipe absent'});
    if (!Item.exists(row.component)) missing.push({recipe: row.id, cause: 'component absent', component: row.component});
  });
  var absent = entrelumenArcaneRemovals.filter(id => !event.containsRecipe({id: id}));
  if (missing.length) {
    console.error('[ENTRELUMEN_ARCANE_BALANCE] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenArcaneSignature, missing: missing}));
    throw new Error('ENTRELUMEN_ARCANE_BALANCE preflight failed; native recipes were not changed');
  }
  entrelumenArcaneRows.forEach(row => {
    event.remove({id: row.id});
    event.custom(row.json).id(row.id);
  });
  entrelumenArcaneRemovals.forEach(id => event.remove({id: id}));
  console.info('[ENTRELUMEN_ARCANE_BALANCE] ' + JSON.stringify({status: 'registered', signature: entrelumenArcaneSignature, changed: entrelumenArcaneRows.length,
    removed: entrelumenArcaneRemovals.length - absent.length, alreadyAbsent: absent}));
});
function entrelumenArcaneFieldCheck(event, row) {
  // Machine recipes that do not expose getIngredients(): test the recipe's own public list field.
  var found = 0;
  try {
    var stack = Item.of(row.component);
    event.forEachRecipe({id: row.id}, holder => {
      holder.value()[row.field].forEach(ingredient => { if (ingredient.test(stack)) found++; });
    });
  } catch (error) {
    console.warn('[ENTRELUMEN_ARCANE_BALANCE] ' + JSON.stringify({status: 'field-check-error', recipe: row.id, error: String(error)}));
    return -1;
  }
  return found;
}
ServerEvents.afterRecipes(event => {
  var failed = [];
  entrelumenArcaneRows.forEach(row => {
    var loaded = event.countRecipes({id: row.id, output: row.output});
    var staged = event.countRecipes({id: row.id, input: row.component});
    if (staged === 0 && row.field) staged = entrelumenArcaneFieldCheck(event, row);
    if (loaded !== 1 || staged !== 1) failed.push({recipe: row.id, loadedOutput: loaded, stagedInput: staged});
  });
  entrelumenArcaneRemovals.forEach(id => { var left = event.countRecipes({id: id}); if (left !== 0) failed.push({recipe: id, remaining: left}); });
  console.info('[ENTRELUMEN_ARCANE_BALANCE] ' + JSON.stringify({status: failed.length ? 'failed-loaded-check' : 'loaded-ingredient-check',
    signature: entrelumenArcaneSignature, checked: entrelumenArcaneRows.length + entrelumenArcaneRemovals.length, failed: failed}));
});
ServerEvents.tags('block', event => {
  event.remove("c:ores_in_ground/deepslate", "forbidden_arcanus:stella_arcanum");
  console.info('[ENTRELUMEN_ARCANE_BALANCE] ' + JSON.stringify({status: 'tags-removed', registry: 'block', count: 1}));
});
ServerEvents.tags('item', event => {
  event.remove("c:ores_in_ground/deepslate", "forbidden_arcanus:stella_arcanum");
  console.info('[ENTRELUMEN_ARCANE_BALANCE] ' + JSON.stringify({status: 'tags-removed', registry: 'item', count: 1}));
});
