_version = 4

[client]
showDhOptionsButtonInMinecraftUi = true

[client.advanced.autoUpdater]
enableAutoUpdater = false
enableSilentUpdates = false

[client.advanced.debugging]
enableDebugKeybindings = false

[client.advanced.graphics]
enableAntiAliasing = true
enableSsao = false

[client.advanced.graphics.culling]
enableCaveCulling = true

[client.advanced.graphics.experimental]
ignoredDimensionCsv = "ad_astra:earth_orbit,ad_astra:glacio,ad_astra:glacio_orbit,ad_astra:mars,ad_astra:mars_orbit,ad_astra:mercury,ad_astra:mercury_orbit,ad_astra:moon,ad_astra:moon_orbit,ad_astra:venus,ad_astra:venus_orbit,ae2:spatial_storage,aether:the_aether,compactmachines:compact_world,deeperdarker:otherside,entrelumen:enves,entrelumen:solsticio,eternal_starlight:starlight,irons_spellbooks:pocket_dimension,jamd:end,jamd:mining,jamd:nether,mahoutsukai:reality_marble,minecraft:the_end,minecraft:the_nether,neovitae:dungeon,the_bumblezone:the_bumblezone,twilightforest:twilight_forest,undergarden:undergarden"

[client.advanced.graphics.genericRendering]
dimensionEnabledCloudRenderingCsv = "minecraft:overworld"
enableCloudRendering = true

[client.advanced.graphics.quality]
ditherDhFade = true
horizontalQuality = "MEDIUM"
lodBiomeBlending = 3
lodChunkRenderDistanceRadius = 128
maxHorizontalResolution = "BLOCK"
transparency = "COMPLETE"
vanillaFadeMode = "DOUBLE_PASS"
verticalQuality = "MEDIUM"

[common.logging.warning]
showExplicitGcDisabledWarning = false
showGarbageCollectorWarning = false
showHighVanillaRenderDistanceWarning = false
showLowMemoryWarningOnStartup = false
showModCompatibilityWarningsOnStartup = false
showPoolInsufficientMemoryWarning = false
showReplayWarningOnStartup = false
showSlowWorldGenSettingWarnings = false
showUpdateQueueOverloadedChatWarning = false

[common.multiThreading]
numberOfThreads = 3
threadRunTimeRatio = 1.0

[common.worldGenerator]
chunkGeneratorMode = "FEATURES"
generatorPlan = "SURFACE_THEN_CHUNKS"
showGenerationProgress = "DISABLED"
