"""Terra's hydroponic garden as a multiblock: a small engine, 3 wide, 2 deep, 2 tall, that forms.

Elias, 29 September 2026: «más chico todavía, y hacé una cosa, hacelo 3x2, hacé una onda tipo Oritech donde
el multiblock se transforma en un modelo propio pero más freestyle estilo Oritech multiblocks».

Unformed it is twelve plain blocks: ten engine casings, one outlet at the back and the core (the pot) in
the middle of the front, on the mirror axis. Woken by the lamp, the members stop drawing themselves and the
core draws one freestyle engine over the whole 3 x 2 x 2 volume (art/authoring/draw_terra_garden.py,
engine_model): the Oritech technique of a hidden member block and a controller model, studied from the pinned
Oritech JAR's machine core and never copied.

Coordinates: x across (mirror-symmetric about x = 0, the middle column), y up, z toward the front (the
drawing faces south, +z); positions are written relative to the core. Every position is required.

Writes companion/src/main/resources/data/entrelumen/terra_garden.json.

    python art/structures/terra_garden.py              # write the layout
    python art/structures/terra_garden.py --check      # compare with the repo
    python art/structures/terra_garden.py --render DIR # review renders (software, not game captures)
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'companion', 'src', 'main', 'resources', 'data', 'entrelumen', 'terra_garden.json')

CORE = 'entrelumen:terra_garden_core'
CASING = 'entrelumen:terra_engine_casing'
OUTLET = 'entrelumen:terra_garden_outlet'


def build():
    """Relative to the core at the front of the middle column, bottom layer."""
    V = {}
    for x in (-1, 0, 1):
        for y in (0, 1):
            for z in (-1, 0):
                V[(x, y, z)] = CASING
    V[(0, 0, 0)] = CORE
    V[(0, 0, -1)] = OUTLET
    return V


def check_symmetry(V):
    for (x, y, z), b in V.items():
        assert V.get((-x, y, z)) == b, ('not mirror-symmetric', (x, y, z), b)


def export(V):
    blocks = [{'pos': [x, y, z], 'block': b}
              for (x, y, z), b in sorted(V.items(), key=lambda kv: (kv[0][1], kv[0][2], kv[0][0]))]
    data = {'name': 'entrelumen:terra_garden', 'anchor': CORE, 'front': 'south',
            'note': 'Generated by art/structures/terra_garden.py. Positions relative to the core; the drawing '
                    'faces south (+z). Every position is required; formed members draw nothing.',
            'blocks': blocks}
    return json.dumps(data, indent=1, ensure_ascii=False) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--render', metavar='DIR')
    args = parser.parse_args()
    V = build()
    check_symmetry(V)
    text = export(V)
    if args.check:
        with open(OUT, encoding='utf-8') as f:
            assert f.read() == text, 'stale ' + OUT
        print(f'PASS: terra_garden.json matches ({len(V)} positions)')
    elif not args.render:
        with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(len(V), 'positions')
    if args.render:
        sys.path.insert(0, HERE)
        import terra_garden_render
        terra_garden_render.render_all(V, args.render)


if __name__ == '__main__':
    main()
