"""Generate a read-only KubeJS item/recipe audit; verify its current runtime receipt.

--sync updates only the diagnostic script. --log requires real KubeJS server.log
or latest.log evidence. A source check alone never claims runtime validation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / 'pack/kubejs/server_scripts/entrelumen_runtime_audit.js'
PREFIX = '[ENTRELUMEN_AUDIT] '
MARKET_SCRIPT = SCRIPT.with_name('entrelumen_market_compat.js')
MARKET_PREFIX = '[ENTRELUMEN_MARKET_COMPAT] '


def market_targets():
    paths = json.loads((ROOT / 'catalog/local-paths.json').read_text(encoding='utf-8'))
    source = next(Path(path) for name, path in paths.items() if name.startswith('farmingforblockheads-'))
    recipes = []
    with zipfile.ZipFile(source) as jar:
        for name in sorted(jar.namelist()):
            if not name.startswith('data/farmingforblockheads/recipe/market/') or not name.endswith('.json'):
                continue
            data = json.loads(jar.read(name))
            if data['type'] != 'farmingforblockheads:market' or not isinstance(data['result'].get('item'), str):
                raise ValueError(f'Unexpected market schema; review instead of silently skipping: {name}')
            recipes.append([name.removeprefix('data/farmingforblockheads/recipe/').removesuffix('.json'), data['result']['item']])
    return {'source': source.name, 'sourceSha256': hashlib.sha256(source.read_bytes()).hexdigest(), 'recipes': recipes}


MARKET_TEMPLATE = '''// Original compatibility guard. No copied prices, presets or recipe bodies.
// Generated by tools/check_runtime_content.py --sync-market from pinned JAR IDs.
const entrelumenMarketTargets = __TARGETS__;
let entrelumenMarketSkipped = [];
let entrelumenMarketRun = '';

ServerEvents.generateData('after_mods', event => {
  entrelumenMarketSkipped = [];
  entrelumenMarketRun = String(Date.now());
  const groups = {};
  entrelumenMarketTargets.recipes.forEach(entry => {
    if (!Item.exists(entry[1])) {
      // KubeJS and NeoForge both evaluate conditions BEFORE the recipe codec.
      // No override is emitted when the original result item is available.
      event.json('farmingforblockheads:recipe/' + entry[0] + '.json', {
        type: 'farmingforblockheads:market',
        'neoforge:conditions': [{type: 'neoforge:false'}]
      });
      entrelumenMarketSkipped.push('farmingforblockheads:' + entry[0]);
      const namespace = entry[1].split(':')[0];
      groups[namespace] = (groups[namespace] || 0) + 1;
    }
  });
  console.info('[ENTRELUMEN_MARKET_COMPAT] ' + JSON.stringify({
    kind: 'generated', run: entrelumenMarketRun,
    sourceSha256: entrelumenMarketTargets.sourceSha256,
    checked: entrelumenMarketTargets.recipes.length,
    skipped: entrelumenMarketSkipped.length,
    untouched: entrelumenMarketTargets.recipes.length - entrelumenMarketSkipped.length,
    groups: groups
  }));
});

ServerEvents.afterRecipes(event => {
  const loaded = {};
  event.forEachRecipe({type: 'farmingforblockheads:market'}, recipe => {
    loaded[String(recipe.getOrCreateId())] = true;
  });
  const unexpected = entrelumenMarketSkipped.filter(id => loaded[id]);
  console.info('[ENTRELUMEN_MARKET_COMPAT] ' + JSON.stringify({
    kind: 'summary', run: entrelumenMarketRun,
    sourceSha256: entrelumenMarketTargets.sourceSha256,
    checked: entrelumenMarketTargets.recipes.length,
    skipped: entrelumenMarketSkipped.length,
    loadedMarketRecipes: Object.keys(loaded).length,
    unexpected: unexpected, status: unexpected.length === 0 ? 'PASS' : 'FAIL'
  }));
});
'''


def verify_market_log(text):
    script = MARKET_SCRIPT.read_text(encoding='utf-8')
    expected = json.loads(script.split('const entrelumenMarketTargets = ', 1)[1].split(';\n', 1)[0])
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if MARKET_PREFIX in line and '"kind":"generated"' in line.replace(' ', '')]
    if not starts:
        raise ValueError('No market compatibility generation receipt; reinstall script and reload')
    current = lines[starts[-1]:]
    rows = [json.loads(line.split(MARKET_PREFIX, 1)[1]) for line in current if MARKET_PREFIX in line]
    if len(rows) != 2 or rows[-1].get('kind') != 'summary':
        raise ValueError('Incomplete or mixed market compatibility receipt')
    generated, summary = rows
    if any(r.get('sourceSha256') != expected['sourceSha256'] or r.get('checked') != len(expected['recipes']) for r in rows):
        raise ValueError('Stale market compatibility receipt')
    if summary.get('run') != generated.get('run') or summary.get('skipped') != generated.get('skipped'):
        raise ValueError('Mixed market compatibility runs')
    if generated['skipped'] + generated['untouched'] != generated['checked']:
        raise ValueError('Market compatibility coverage mismatch')
    if sum(generated['groups'].values()) != generated['skipped']:
        raise ValueError('Market compatibility group count mismatch')
    if summary.get('status') != 'PASS' or summary.get('unexpected') != []:
        raise ValueError('Invalid market recipes survived conditional filtering')
    if any('farmingforblockheads:market/' in line and re.search(r'error|exception|failed', line, re.I) for line in current):
        raise ValueError('Market recipe parsing errors remain in current runtime cycle')
    return {'checked': generated['checked'], 'skipped': generated['skipped'], 'untouched': generated['untouched'], 'loadedMarketRecipes': summary['loadedMarketRecipes']}


def targets():
    chapter = json.loads((ROOT / 'pack/config/ftbquests/quests/chapters/a_light_among_ruins.snbt').read_text(encoding='utf-8-sig'))
    projects = json.loads((ROOT / 'companion/src/main/resources/data/entrelumen/campaign/projects.json').read_text(encoding='utf-8-sig'))
    items = set()

    def collect(value):
        if isinstance(value, dict):
            item_id = value.get('id', '')
            if re.fullmatch(r'[a-z0-9_.-]+:[a-z0-9_./-]+', item_id):
                items.add(item_id)
            for child in value.values():
                collect(child)
        elif isinstance(value, list):
            for child in value:
                collect(child)

    collect(chapter)
    for project in projects.values():
        if project['act'] == 1:
            items.update(project['items'])
            if project.get('reward'):
                items.add(project['reward'])
    # Verify proposed cross-mod ingredients before implementing their recipes.
    # These are existing third-party IDs, not unregistered proposed components.
    design_path = ROOT / 'content/integration-design.json'
    if design_path.exists():
        design = json.loads(design_path.read_text(encoding='utf-8'))
        for evidence in design['itemEvidence']:
            item_id = evidence['itemId']
            if not re.fullmatch(r'[a-z0-9_.-]+:[a-z0-9_./-]+', item_id):
                raise ValueError(f'Invalid integration ingredient ID: {item_id}')
            items.add(item_id)
    recipes = []
    for path in sorted((ROOT / 'companion/src/main/resources/data/entrelumen/recipe').glob('*.json')):
        output = json.loads(path.read_text(encoding='utf-8'))['result']['id']
        if output in items:
            recipes.append({'id': 'entrelumen:' + path.stem, 'output': output})
    # These exact recipe IDs and outputs were inspected in Farmer's Delight 1.3.3.
    for name in ('flint_knife', 'cutting_board'):
        item_id = 'farmersdelight:' + name
        if item_id in items:
            recipes.append({'id': item_id, 'output': item_id})
    result = {'schema': 1, 'items': sorted(items), 'recipes': sorted(recipes, key=lambda r: r['id'])}
    result['signature'] = hashlib.sha256(json.dumps(result, sort_keys=True).encode()).hexdigest()[:16]
    return result


TEMPLATE = '''// Read-only: no recipe edits, inventory writes, progress or rewards.
// KubeJS 2101.7.2-build.374. API evidence: ../README.md.
// Generated by tools/check_runtime_content.py --sync; do not edit targets by hand.
const entrelumenAuditTargets = __TARGETS__;

ServerEvents.afterRecipes(event => {
  const targets = entrelumenAuditTargets;
  const run = String(Date.now());
  let failures = 0;
  const emit = row => {
    row.run = run;
    row.signature = targets.signature;
    console.info('[ENTRELUMEN_AUDIT] ' + JSON.stringify(row));
  };
  emit({kind: 'begin', items: targets.items.length, recipes: targets.recipes.length});
  targets.items.forEach(id => {
    const exists = Item.exists(id);
    if (!exists) failures++;
    emit({kind: 'item', id: id, exists: exists});
  });
  targets.recipes.forEach(spec => {
    // Filter evaluates the loaded recipe, not the source JSON or a guessed result.
    const matches = event.countRecipes({id: spec.id, output: spec.output});
    const alternatives = [];
    event.forEachRecipe({output: spec.output}, recipe => {
      alternatives.push(String(recipe.getOrCreateId()));
    });
    alternatives.sort();
    if (matches !== 1) failures++;
    emit({kind: 'recipe', id: spec.id, output: spec.output, matches: matches,
      alternatives: alternatives.slice(0, 64), alternativesTotal: alternatives.length});
  });
  emit({kind: 'summary', items: targets.items.length, recipes: targets.recipes.length,
    failures: failures, status: failures === 0 ? 'PASS' : 'FAIL'});
});
'''


def verify_log(text, expected):
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if PREFIX in line and '"kind":"begin"' in line.replace(' ', '')]
    if not starts:
        raise ValueError('No runtime audit begin marker; script did not complete loading or was not installed')
    current = lines[starts[-1]:]
    rows = []
    for line in current:
        if PREFIX in line:
            rows.append(json.loads(line.split(PREFIX, 1)[1]))
        elif re.search(r'\bERROR\b|\bFATAL\b|\b[1-9][0-9]* errors?\b', line, re.I):
            # For KubeJS-specific logs, any error is material. For latest.log this
            # intentionally also flags server errors after the audit begins.
            raise ValueError('Runtime error after audit began; inspect supplied log')
    if not rows or rows[-1].get('kind') != 'summary':
        raise ValueError('Incomplete runtime audit (missing terminal summary)')
    run = rows[0]['run']
    if any(r.get('run') != run or r.get('signature') != expected['signature'] for r in rows):
        raise ValueError('Stale or mixed audit receipt; reinstall current script and restart/reload')
    item_rows = [r for r in rows if r['kind'] == 'item']
    recipe_rows = [r for r in rows if r['kind'] == 'recipe']
    if sorted(r['id'] for r in item_rows) != expected['items']:
        raise ValueError('Item coverage differs from current first-hour references')
    observed = sorted([{'id': r['id'], 'output': r['output']} for r in recipe_rows], key=lambda r: r['id'])
    if observed != expected['recipes']:
        raise ValueError('Recipe/output coverage differs from current references')
    missing = [r['id'] for r in item_rows if r.get('exists') is not True]
    missing += [r['id'] for r in recipe_rows if r.get('matches') != 1]
    summary = rows[-1]
    if missing or summary.get('failures') != 0 or summary.get('status') != 'PASS':
        raise ValueError('Runtime content missing/mismatched: ' + ', '.join(missing))
    if summary.get('items') != len(item_rows) or summary.get('recipes') != len(recipe_rows):
        raise ValueError('Summary coverage mismatch')
    return {'items': len(item_rows), 'recipes': len(recipe_rows), 'signature': expected['signature'], 'run': run}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sync', action='store_true')
    parser.add_argument('--sync-market', action='store_true')
    parser.add_argument('--log', type=Path)
    args = parser.parse_args()
    if args.sync_market:
        MARKET_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
        market = market_targets()
        MARKET_SCRIPT.write_text(MARKET_TEMPLATE.replace('__TARGETS__', json.dumps(market, ensure_ascii=False, separators=(',', ':'))), encoding='utf-8')
        print(f"Generated compatibility guard for {len(market['recipes'])} market references; missing results decided by actual runtime registry.")
    expected = targets()
    script = TEMPLATE.replace('__TARGETS__', json.dumps(expected, ensure_ascii=False, indent=2))
    if args.sync:
        SCRIPT.parent.mkdir(parents=True, exist_ok=True)
        SCRIPT.write_text(script, encoding='utf-8')
    if not SCRIPT.exists() or SCRIPT.read_text(encoding='utf-8') != script:
        raise ValueError('Diagnostic script targets are stale; run --sync and reinstall before runtime audit')
    if args.log:
        log = args.log.read_text(encoding='utf-8-sig', errors='replace')
        result = verify_log(log, expected)
        if MARKET_SCRIPT.exists():
            result['market'] = verify_market_log(log)
        print('PASS runtime: ' + json.dumps(result))
    else:
        print(f"PASS source coverage only: {len(expected['items'])} item IDs, {len(expected['recipes'])} recipe/output pairs. Runtime evidence still required with --log.")
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (ValueError, OSError, KeyError) as error:
        print(f'FAIL: {error}', file=sys.stderr)
        sys.exit(1)
