"""Keep five Malum 1.8.2 recipes working without copying Malum's files.

Malum is all rights reserved, and its Occultism chalk repairs and grim talc milling ship with stale field names
(`inputs` for `validItems`; `item` for `id` in the Create results). The five upstream files are written as the
false condition alone, and ServerEvents.recipes adds ENTRELUMEN's own recipes at the same IDs from the specs
below. --check reads the pinned JAR and fails unless each upstream file is still stale in exactly that way and
equal to our spec once the stale keys are put back, so the mechanics are the native ones and nothing else.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "pack/kubejs/data/malum/recipe"
SCRIPT = ROOT / "pack/kubejs/server_scripts/entrelumen_malum_compat.js"
STUB = {"neoforge:conditions": [{"type": "neoforge:false"}]}
COLORS = ("gold", "purple", "red", "white")
PREFIX = "malum/spirit_repair/occultism/"
MILLING = "create/milling/grim_talc.json"


def chalk_repair(color, material, count):
    """Our recipe for the Repair Pylon to restore one Occultism chalk: full durability for eight arcane spirits."""
    return {"type": "malum:spirit_repair", "durabilityPercentage": 1, "repairMaterial": {"count": count, **material},
            "spirits": [{"type": "malum:arcane", "count": 8}], "validItems": ["occultism:chalk_" + color]}


# relative recipe path -> (mod that must be loaded, our recipe)
SPECS = {
    PREFIX + "gold_chalk.json": ("occultism", chalk_repair("gold", {"tag": "c:dusts/gold"}, 1)),
    PREFIX + "purple_chalk.json": ("occultism", chalk_repair("purple", {"tag": "c:dusts/obsidian"}, 2)),
    PREFIX + "red_chalk.json": ("occultism", chalk_repair("red", {"item": "occultism:afrit_essence"}, 1)),
    PREFIX + "white_chalk.json": ("occultism", chalk_repair("white", {"item": "occultism:burnt_otherstone"}, 1)),
    MILLING: ("create", {"type": "create:milling", "ingredients": [{"item": "malum:grim_talc"}], "processing_time": 100,
                         "results": [{"count": 6, "id": "minecraft:bone_meal"},
                                     {"chance": 0.25, "id": "minecraft:yellow_dye"},
                                     {"chance": 0.25, "count": 4, "id": "minecraft:bone_meal"}]}),
}


def stale(recipe):
    """The upstream form of one of our recipes: the keys 1.21.1 no longer reads, put back."""
    old = json.loads(json.dumps(recipe))
    if old["type"] == "create:milling":
        for result in old["results"]:
            result["item"] = result.pop("id")
    else:
        old["inputs"] = old.pop("validItems")
    return old


def recipe_id(relative):
    return "malum:" + relative.removesuffix(".json")


def render_script():
    rows = {recipe_id(relative): {"mod": mod, "json": recipe} for relative, (mod, recipe) in SPECS.items()}
    lines = [
        "// Generated by tools/generate_malum_compat.py: ENTRELUMEN's own versions of five Malum recipes whose files",
        "// ship stale (their data files are disabled; nothing of Malum's files is copied).",
        "const entrelumenMalumCompatRecipes = " + json.dumps(rows, separators=(",", ":")) + ";",
        "ServerEvents.recipes(event => {",
        "  // One recipe at a time: a row KubeJS rejects is reported (failed-row) and does not stop the next.",
        "  var failedRows = [];",
        "  Object.keys(entrelumenMalumCompatRecipes).forEach(id => {",
        "    var row = entrelumenMalumCompatRecipes[id];",
        "    if (Platform.isLoaded(row.mod) && !entrelumenAddRecipe(event, 'ENTRELUMEN_MALUM_COMPAT', null, id, row.json)) failedRows.push(id);",
        "  });",
        "  if (failedRows.length) {",
        "    console.warn('[ENTRELUMEN_MALUM_COMPAT] ' + JSON.stringify({status: 'registered-with-failed-rows', failedRows: failedRows}));",
        "  }",
        "});",
    ]
    return "\n".join(lines) + "\n"


def generate(write=False, log=None, audit_token=None):
    lock = json.loads((ROOT / "catalog/curated.json").read_text(encoding="utf-8"))
    paths = json.loads((ROOT / "catalog/local-paths.json").read_text(encoding="utf-8"))
    entry = next(e for e in lock["mods"] if any(m["id"] == "malum" for m in e["metadata"]["mods"]))
    source = Path(paths[entry["filename"]])
    if hashlib.sha256(source.read_bytes()).hexdigest() != entry["sha256"]:
        raise ValueError("Malum JAR differs from lock")
    errors = []
    inventory = []
    expected = {}
    with zipfile.ZipFile(source) as jar:
        schema = json.loads(jar.read("data/malum/kubejs/recipe_schema/spirit_repair.json"))
        assert "validItems" in [k["name"] for k in schema["keys"]]
        for relative, (mod, recipe) in SPECS.items():
            original = json.loads(jar.read("data/malum/recipe/" + relative))
            if original.get("neoforge:conditions") != [{"type": "neoforge:mod_loaded", "modid": mod}]:
                raise ValueError("Upstream condition changed; review obsolete patch: " + relative)
            if any(key in original for key in ("validItems",)) or (
                    recipe["type"] == "malum:spirit_repair" and original.get("inputs") != recipe["validItems"]):
                raise ValueError("Upstream changed; review obsolete patch: " + relative)
            assert original["type"] == recipe["type"]
            if recipe["type"] == "create:milling":
                assert len(original["results"]) == 3
                if any("id" in result or "item" not in result for result in original["results"]):
                    raise ValueError("Upstream milling result changed")
            # Every mechanic and condition is the native one: our recipe with its stale keys back is the file.
            assert {**stale(recipe), "neoforge:conditions": original["neoforge:conditions"]} == original, relative
            # KubeJS reads a recipe file's `type` before its load conditions; without one it logs "not a json object" on every load.
            text = json.dumps({**STUB, "type": recipe["type"]}, indent=2) + "\n"
            expected[recipe_id(relative)] = {k: v for k, v in recipe.items() if k != "type"}
            inventory.append((recipe_id(relative), hashlib.sha256(jar.read("data/malum/recipe/" + relative)).hexdigest(),
                              hashlib.sha256(json.dumps(recipe, sort_keys=True).encode()).hexdigest()))
            target = DATA / relative
            if write:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(text, encoding="utf-8", newline="\n")
            if not target.exists() or target.read_text(encoding="utf-8") != text:
                errors.append(str(target.relative_to(ROOT)))
    script = render_script()
    if write:
        SCRIPT.write_text(script, encoding="utf-8", newline="\n")
    elif not SCRIPT.exists() or SCRIPT.read_text(encoding="utf-8") != script:
        errors.append(str(SCRIPT.relative_to(ROOT)))
    if errors:
        raise ValueError("Missing or stale generated files: " + ", ".join(errors))
    audit = ROOT / "pack/kubejs/server_scripts/entrelumen_malum_audit.js"
    if audit_token:
        import re
        if not re.fullmatch(r"[A-Za-z0-9_-]{8,80}", audit_token):
            raise ValueError("Use a unique audit token of 8-80 safe characters")
        signature = hashlib.sha256(json.dumps(expected, sort_keys=True).encode()).hexdigest()
        script = "// Generated read-only RecipeManager audit; never modifies recipes.\n"
        script += "const elMalumAuditToken = " + json.dumps(audit_token) + ";\n"
        script += "const elMalumAuditSignature = " + json.dumps(signature) + ";\n"
        script += "const elMalumAuditExpected = " + json.dumps(expected) + ";\n"
        script += MALUM_AUDIT_JS
        if write:
            audit.write_text(script, encoding="utf-8", newline="\n")
        elif not audit.exists() or audit.read_text(encoding="utf-8") != script:
            raise ValueError("Audit script stale: generate/install a fresh token before reload")
    if log:
        if not audit_token:
            raise ValueError("--log requires the fresh --audit-token installed before this reload")
        check_receipt(Path(log), audit_token, signature, expected)
    for row in inventory:
        print(" | ".join(row))
    print("PASS: five exact recipe IDs; source hash, native schema and all non-key semantics preserved; no file of Malum copied.")

MALUM_AUDIT_JS = r"""
entrelumenAfterRecipes('ENTRELUMEN_MALUM_AUDIT', index => {
  var ops = Java.loadClass('com.mojang.serialization.JsonOps').INSTANCE;
  var run = String(Date.now());
  var emit = row => {
    row.token = elMalumAuditToken; row.signature = elMalumAuditSignature; row.run = run;
    console.info('[ENTRELUMEN_MALUM_AUDIT] ' + JSON.stringify(row));
  };
  emit({kind: 'begin'});
  var failures = 0;
  Object.keys(elMalumAuditExpected).forEach(id => {
    var count = 0;
    try {
      var holder = index.holder(id);
      if (holder) {
        count++;
        var encoded = holder.getSerializer().codec().codec().encodeStart(ops, holder.getRecipe()).getOrThrow();
        emit({kind: 'recipe', id: id, actual: JSON.parse(String(encoded))});
      }
      if (count !== 1) { failures++; emit({kind: 'error', id: id, count: count}); }
    } catch (error) { failures++; emit({kind: 'error', id: id, message: String(error)}); }
  });
  emit({kind: 'summary', count: 5, failures: failures});
});
"""


def check_receipt(path, token, signature, expected):
    marker = "[ENTRELUMEN_MALUM_AUDIT] "
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    records = [(i, json.loads(line.split(marker, 1)[1])) for i, line in enumerate(lines) if marker in line]
    starts = [(i, r) for i, r in records if r.get("kind") == "begin"]
    if not starts:
        raise ValueError("No actual RecipeManager audit receipt")
    start, begin = starts[-1]  # Never fall back to an older successful run.
    if begin.get("token") != token or begin.get("signature") != signature:
        raise ValueError("Latest audit is stale or has a different installed payload")
    rows = [r for i, r in records if i >= start]
    if any(r.get("run") != begin["run"] or r.get("token") != token or r.get("signature") != signature for r in rows):
        raise ValueError("Mixed audit runs")
    if rows[-1].get("kind") != "summary" or rows[-1].get("failures") != 0:
        raise ValueError("Latest audit incomplete or failed")
    recipes = [r for r in rows if r.get("kind") == "recipe"]
    if len(recipes) != 5 or {r["id"] for r in recipes} != set(expected):
        raise ValueError("Five exact live recipes were not observed")
    # Codec may emit optional defaults; every expected semantic field must match.
    for row in recipes:
        for key, value in expected[row["id"]].items():
            actual = row["actual"].get(key)
            if key == "repairMaterial":
                value = dict(value, count=value.get("count", 1))
                actual = dict(actual or {}, count=(actual or {}).get("count", 1))
            if key == "results":
                value = [dict(v, count=v.get("count", 1), chance=v.get("chance", 1)) for v in value]
                actual = [dict(v, count=v.get("count", 1), chance=v.get("chance", 1)) for v in (actual or [])]
            if actual != value:
                raise ValueError(f"Live field mismatch: {row['id']} {key}")
    # A later reload start invalidates a receipt until that reload produces its own audit.
    import re
    if any(re.search(r"Reloading ResourceManager|Reloading resources|Reloading!", line) for line in lines[records[-1][0] + 1:]):
        raise ValueError("A newer reload started after the receipt")
    print("PASS live RecipeManager: five IDs and all expected semantic fields; latest run/token verified")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true", help="Check deterministic outputs (default)")
    parser.add_argument("--log", type=Path, help="Fresh post-fix log with RecipeManager receipt")
    parser.add_argument("--audit-token", help="Unique token generated and installed before reload")
    args = parser.parse_args()
    generate(args.write, args.log, args.audit_token)
