"""Generate/check the 22 static integration recipes; never writes a live instance."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "content/integration-design.json"
TARGET = ROOT / "pack/kubejs/server_scripts/entrelumen_integration_recipes.js"
ID = re.compile(r"^[a-z0-9_.-]+:[a-z0-9_./-]+$")


def recipes_from(design):
    projects = design["projects"]
    if len(projects) != 22:
        raise ValueError("Expected 22 integration projects")
    rows, outputs, ids = [], {}, set()
    for project in projects:
        recipe, output = project["recipe"], project["output"]
        rid = recipe["id"]
        if not ID.fullmatch(rid) or not rid.startswith("entrelumen:integration/") or rid in ids:
            raise ValueError(f"Invalid/duplicate reserved recipe ID: {rid}")
        ids.add(rid)
        if recipe["type"] != "minecraft:crafting_shapeless":
            raise ValueError(f"Unsupported recipe type: {rid}")
        if set(project["title"]) != {"en_us", "es_es"} or not all(isinstance(v, str) and v.strip() for v in project["title"].values()):
            raise ValueError(f"Missing bilingual project title: {rid}")
        if not ID.fullmatch(output["id"]) or not output["id"].startswith("entrelumen:") or output["id"] in outputs:
            raise ValueError(f"Invalid/duplicate output: {rid}")
        if type(output["count"]) is not int or not 1 <= output["count"] <= 64:
            raise ValueError(f"Invalid yield: {rid}")
        ingredients = []
        for entry in recipe["inputs"]:
            if not ID.fullmatch(entry["id"]) or type(entry["count"]) is not int or not 1 <= entry["count"] <= 9:
                raise ValueError(f"Invalid ingredient: {rid}: {entry}")
            ingredients.extend([{"item": entry["id"]}] * entry["count"])
        if not 1 <= len(ingredients) <= 9:
            raise ValueError(f"Crafting grid overflow/empty: {rid}")
        outputs[output["id"]] = project
        rows.append({"id": rid, "json": {"type": "minecraft:crafting_shapeless", "category": "misc", "ingredients": ingredients, "result": {"id": output["id"], "count": output["count"]}}})
    visiting, visited = set(), set()
    def visit(item):
        if item in visiting:
            raise ValueError(f"Circular component dependency: {item}")
        if item in visited:
            return
        visiting.add(item)
        for entry in outputs[item]["recipe"]["inputs"]:
            if entry["id"] in outputs:
                visit(entry["id"])
        visiting.remove(item)
        visited.add(item)
    for item in outputs:
        visit(item)
    return rows


def check_existing_ids(rows):
    reserved = {row["id"] for row in rows}
    for base in [ROOT / "companion/src/main/resources/data", ROOT / "pack/kubejs/data"]:
        if not base.exists():
            continue
        for path in base.glob("*/recipe/**/*.json"):
            rel = path.relative_to(base)
            rid = rel.parts[0] + ":" + "/".join(rel.parts[2:])[:-5]
            if rid in reserved:
                raise ValueError(f"Existing source recipe would be replaced: {rid} ({path})")


def render(rows):
    payload = json.dumps(rows, ensure_ascii=False, indent=2)
    signature = hashlib.sha256(payload.encode()).hexdigest()
    return "// Generated by tools/generate_integration_recipes.py --write; do not edit.\n// Static native recipes; no team, act, gifts, reward or inventory handlers.\nconst entrelumenIntegrationSignature = " + json.dumps(signature) + ";\nconst entrelumenIntegrationRecipes = " + payload + ";\n" + RUNTIME


RUNTIME = r"""
ServerEvents.recipes(event => {
  const errors = [];
  entrelumenIntegrationRecipes.forEach(row => {
    const ids = [row.json.result.id].concat(row.json.ingredients.map(i => i.item));
    ids.forEach(id => {
      if (!Item.exists(id)) errors.push({recipe: row.id, missingItem: id});
    });
    if (event.containsRecipe({id: row.id})) errors.push({recipe: row.id, collision: true});
  });
  if (errors.length) {
    console.error('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify({status: 'failed-preflight', signature: entrelumenIntegrationSignature, added: 0, errors: errors}));
    throw new Error('ENTRELUMEN integration recipes preflight failed; see contextual errors. No integration recipes were added.');
  }
  entrelumenIntegrationRecipes.forEach(row => event.custom(row.json).id(row.id));
  console.info('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify({status: 'registered', signature: entrelumenIntegrationSignature, recipes: entrelumenIntegrationRecipes.length}));
});

ServerEvents.afterRecipes(event => {
  const missing = [];
  entrelumenIntegrationRecipes.forEach(row => {
    if (event.countRecipes({id: row.id, output: row.json.result.id}) !== 1) missing.push(row.id);
  });
  const receipt = {status: missing.length ? 'failed-loaded-check' : 'loaded', signature: entrelumenIntegrationSignature, checked: entrelumenIntegrationRecipes.length, missing: missing};
  if (missing.length) console.error('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify(receipt));
  else console.info('[ENTRELUMEN_INTEGRATION] ' + JSON.stringify(receipt));
});
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = ap.parse_args()
    rows = recipes_from(json.loads(SOURCE.read_text(encoding="utf-8")))
    check_existing_ids(rows)
    expected = render(rows)
    if args.write:
        TARGET.write_text(expected, encoding="utf-8")
    elif not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
        raise ValueError("Generated script differs from source; run --write")
    print("PASS: 22 static recipes, valid native grids/yields, bilingual project titles, component DAG, reserved IDs and source parity. Crafting runtime not tested.")


if __name__ == "__main__":
    main()
