"""Generate the shared KubeJS helpers every ENTRELUMEN recipe script calls.

All server scripts of a KubeJS pack run in one top-level scope, and a file with `// priority: N` loads before the
files of a lower priority, so `entrelumen_recipe_tools.js` loads first and the generated balance scripts call its
functions from their events. It holds what must not be repeated in every script:

  * entrelumenReplaceRecipe / entrelumenAddRecipe / entrelumenRemoveRecipe: one recipe row at a time. The
    replacement is built first (RecipesKubeEvent.custom) and the native recipe goes only once that worked, so a
    row KubeJS cannot parse leaves the native recipe where it was, logs one `failed-row` line with the recipe ID
    and lets the next row run.

usage: generate_recipe_tools.py --write | --check
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'pack/kubejs/server_scripts/entrelumen_recipe_tools.js'

HEADER = '''// priority: 1000
// Generated by tools/generate_recipe_tools.py; edit that file, not this one.
// Shared helpers of the ENTRELUMEN recipe scripts. KubeJS runs every server script in one top-level scope and loads
// the higher priority first, so the other scripts call these from their events. Plain var and function on purpose:
// Rhino build.91 mishandles block-scoped const in repeated callbacks.
'''

HELPERS = '''
function entrelumenRecipeFailure(tag, signature, recipe, stage, error) {
  console.error('[' + tag + '] ' + JSON.stringify({status: 'failed-row', signature: signature, recipe: String(recipe),
    stage: stage, error: String(error)}));
}

// Replace (or add) one recipe. The replacement is built first and the native recipe is removed only if that worked:
// RecipesKubeEvent.custom throws for JSON it cannot read at all (no type, unknown type) and, for a type's own schema
// rejecting the fields (a Modern Industrialization machine, say), logs the error and returns a recipe it never
// registered (creationError). Either way the native recipe stays and the row reports `failed-row`.
function entrelumenCustomRecipe(event, tag, signature, id, json, removeNative) {
  var stage = 'build';
  var added = null;
  try {
    added = event.custom(json);
    if (!added || added.creationError === true) throw new Error('KubeJS rejected the recipe JSON (see the error above)');
    stage = 'id';
    added.id(id);
    if (removeNative) {
      stage = 'remove-native';
      event.remove({id: id});
    }
    return true;
  } catch (error) {
    entrelumenRecipeFailure(tag, signature, id, stage, error);
    if (added) {
      try { added.remove(); } catch (ignored) { /* the row is reported; nothing else to undo */ }
    }
    return false;
  }
}
function entrelumenReplaceRecipe(event, tag, signature, id, json) {
  return entrelumenCustomRecipe(event, tag, signature, id, json, true);
}
function entrelumenAddRecipe(event, tag, signature, id, json) {
  return entrelumenCustomRecipe(event, tag, signature, id, json, false);
}
function entrelumenRemoveRecipe(event, tag, signature, id) {
  try {
    event.remove({id: id});
    return true;
  } catch (error) {
    entrelumenRecipeFailure(tag, signature, id, 'remove', error);
    return false;
  }
}
'''


def render() -> str:
    return HEADER + HELPERS


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--write', action='store_true')
    group.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = render()
    if args.write:
        TARGET.write_text(text, encoding='utf-8', newline='\n')
    elif not TARGET.exists() or TARGET.read_text(encoding='utf-8') != text:
        raise SystemExit(f'Generated {TARGET.name} is stale; run --write')
    print(f'PASS {TARGET.name}: {len(text.splitlines())} lines')


if __name__ == '__main__':
    main()
