"""ENTRELUMEN jetpack balance: every jetpack pays 2.5 times its native energy per tick (Elias, 25 September 2026).

Reads content/jetpack-balance.json (the pinned mods' defaults) and writes:
  pack/config/ironjetpacks/jetpacks/<type>.json  Iron Jetpacks reads every type from that folder and writes its
      defaults only when the folder is missing, so the pack ships all of them: the defaults with `usage` raised.
  pack/config/oritech-startup.toml, pack/config/pneumaticcraft-common.toml  partial NeoForge configs; NeoForge
      fills in every other key with its default on the first start.
  pack/kubejs/server_scripts/entrelumen_jetpack_balance.js  the surcharge for the jetpacks whose per-tick cost is
      fixed in code: after each player tick it takes 1.5 times what the worn chest piece lost since the last one.
  the before/after table of docs/design/recipe-design-rules.md, between its jetpack-table markers.

usage: generate_jetpack_balance.py --write | --check
"""
from __future__ import annotations

import argparse
from fractions import Fraction
import json
import math
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'content/jetpack-balance.json'
DOC = ROOT / 'docs/design/recipe-design-rules.md'
START, END = '<!-- jetpack-table:start -->', '<!-- jetpack-table:end -->'
HEADER = '// Generated by tools/generate_jetpack_balance.py from content/jetpack-balance.json; edit those, not this file.'


def load() -> dict:
    return json.loads(DATA.read_text(encoding='utf-8'))


def raised(value: int, factor: Fraction) -> int:
    """The new integer setting: at least factor times the default."""
    return math.ceil(Fraction(value) * factor)


def number(value) -> str:
    """Spanish decimal comma for the doc table."""
    return str(value).replace('.', ',')


def iron_jetpacks(data: dict, factor: Fraction) -> dict[str, str]:
    section = data['ironjetpacks']
    out = {}
    for name, default in section['defaults'].items():
        jetpack = dict(default)
        jetpack[section['field']] = raised(default[section['field']], factor)
        out[f"pack/config/ironjetpacks/jetpacks/{name}.json"] = json.dumps(jetpack, indent=2) + '\n'
    return out


def configs(data: dict, factor: Fraction) -> dict[str, str]:
    files: dict[str, list[str]] = {}
    for entry in data['configs']:
        lines = files.setdefault(entry['file'], [
            f"# ENTRELUMEN: jetpacks pay {data['factor']} times their native cost per tick (tools/generate_jetpack_balance.py).",
            '# NeoForge fills in every other key with its default on the first start.',
        ])
        lines += ['', f"[{entry['section']}]"]
        for key, (default, _) in entry['settings'].items():
            lines.append(f"\t# mod default {default}")
            lines.append(f"\t{key} = {raised(default, factor)}")
    return {f'pack/config/{name}': '\n'.join(lines) + '\n' for name, lines in files.items()}


def script(data: dict, factor: Fraction) -> str:
    surcharge = data['surcharge']
    table = {row['item']: {'kind': row['kind'], 'max': row['max']} for row in surcharge['items']}
    extra = factor - 1
    extra_text = str(float(extra)).rstrip('0').rstrip('.')
    rows = ',\n'.join(f"  {json.dumps(item)}: {json.dumps(spec)}" for item, spec in table.items())
    return f"""{HEADER}
// ENTRELUMEN jetpack balance (Elias, 25 September 2026): every jetpack pays {data['factor']} times its native energy per
// tick. Iron Jetpacks, Oritech and the PneumaticCraft Jet Boots read it from pack/config. The pieces below fix their
// per-tick cost in code, so after each player tick this script takes {extra_text} times what the worn chest piece lost
// since the previous tick, once the mod has taken its own share. A loss above the piece's native maximum per tick is a
// swap, not flight, and is not charged; a tick in which something also charged the piece is not charged either.
const entrelumenJetpackSurcharge = {{
{rows}
}};
const entrelumenJetpackExtra = {extra_text};
const entrelumenJetpackSeen = {{}};
var entrelumenJetpackApi = null;
var entrelumenJetpackBroken = false;

function entrelumenJetpackLoad() {{
  if (entrelumenJetpackApi !== null) return entrelumenJetpackApi;
  var api = {{}};
  api.chest = Java.loadClass('net.minecraft.world.entity.EquipmentSlot').CHEST;
  api.items = Java.loadClass('net.minecraft.core.registries.BuiltInRegistries').ITEM;
  api.energy = Java.loadClass('net.neoforged.neoforge.capabilities.Capabilities$EnergyStorage').ITEM;
  api.fluid = Java.loadClass('net.neoforged.neoforge.capabilities.Capabilities$FluidHandler').ITEM;
  api.fluidExecute = Java.loadClass('net.neoforged.neoforge.fluids.capability.IFluidHandler$FluidAction').EXECUTE;
  api.chemical = null;
  if (Platform.isLoaded('mekanism')) {{
    api.chemical = Java.loadClass('mekanism.common.capabilities.Capabilities').CHEMICAL.item();
    api.chemicalExecute = Java.loadClass('mekanism.api.Action').EXECUTE;
  }}
  entrelumenJetpackApi = api;
  return api;
}}

// What the worn piece holds of its fuel (energy, fluid or hydrogen) and how to take some of it; null if it has no store.
function entrelumenJetpackStore(api, stack, kind) {{
  if (kind === 'energy') {{
    var energy = stack.getCapability(api.energy);
    if (energy === null) return null;
    return {{amount: Number(energy.getEnergyStored()), take: n => Number(energy.extractEnergy(n, false))}};
  }}
  if (kind === 'fluid') {{
    var fluid = stack.getCapability(api.fluid);
    if (fluid === null || fluid.getTanks() < 1) return null;
    var inTank = fluid.getFluidInTank(0);
    // Drain by FluidStack: drain(int, action) and drain(FluidStack, action) could both take a JS number.
    return {{amount: Number(inTank.getAmount()),
      take: n => Number(fluid.drain(inTank.copyWithAmount(n), api.fluidExecute).getAmount())}};
  }}
  if (kind === 'chemical' && api.chemical !== null) {{
    var chemical = stack.getCapability(api.chemical);
    if (chemical === null) return null;
    var tanks = [];
    var total = 0;
    for (var tank = 0; tank < chemical.getChemicalTanks(); tank++) {{
      var held = chemical.getChemicalInTank(tank);
      if (held.isEmpty() || String(held.getTypeRegistryName()) !== 'mekanism:hydrogen') continue;
      tanks.push(tank);
      total += Number(held.getAmount());
    }}
    var item = stack.getItem();
    return {{amount: total, take: n => {{
      // Mekanism's jetpacks let hydrogen out only by hand (IChemicalItem.useChemical, AutomationType.MANUAL),
      // the way their own useJetpackFuel takes it; the MekaSuit's tanks answer the capability.
      if (typeof item.useChemical === 'function') return Number(item.useChemical(stack, n).getAmount());
      var taken = 0;
      tanks.forEach(index => {{
        if (taken < n) taken += Number(chemical.extractChemical(index, n - taken, api.chemicalExecute).getAmount());
      }});
      return taken;
    }}}};
  }}
  return null;
}}

// seen is what the same player wore on the previous tick ({{id, amount, carry}}) or undefined.
// Returns [whole units to take now, the fraction carried to the next tick].
function entrelumenJetpackCharge(seen, id, amount, max) {{
  if (!seen || seen.id !== id) return [0, 0];
  var lost = seen.amount - amount;
  if (lost <= 0 || lost > max) return [0, seen.carry];
  var owed = seen.carry + lost * entrelumenJetpackExtra;
  var whole = Math.floor(owed);
  return [whole, owed - whole];
}}

PlayerEvents.tick(event => {{
  if (entrelumenJetpackBroken) return;
  try {{
    // KubeJS exposes Entity.getStringUUID to scripts as getStringUuid.
    var key = String(event.player.getStringUuid());
    var api = entrelumenJetpackLoad();
    var stack = event.player.getItemBySlot(api.chest);
    var id = stack.isEmpty() ? '' : String(api.items.getKey(stack.getItem()));
    var spec = entrelumenJetpackSurcharge[id];
    var store = spec ? entrelumenJetpackStore(api, stack, spec.kind) : null;
    if (store === null) {{
      delete entrelumenJetpackSeen[key];
      return;
    }}
    var charge = entrelumenJetpackCharge(entrelumenJetpackSeen[key], id, store.amount, spec.max);
    var amount = store.amount;
    if (charge[0] > 0) amount -= store.take(charge[0]);
    entrelumenJetpackSeen[key] = {{id: id, amount: amount, carry: charge[1]}};
  }} catch (error) {{
    // One report, then the surcharge stays off until the next reload instead of failing every tick.
    entrelumenJetpackBroken = true;
    console.error('ENTRELUMEN jetpack surcharge disabled: ' + error);
  }}
}});

PlayerEvents.loggedOut(event => {{
  delete entrelumenJetpackSeen[String(event.player.getStringUuid())];
}});
"""


def table(data: dict, factor: Fraction) -> str:
    ij = data['ironjetpacks']
    lines = [START, '', '| Jetpack | Mod | Ajuste | Antes | Después |', '|---|---|---|---|---|']
    for name, default in ij['defaults'].items():
        value = default[ij['field']]
        lines.append(f"| {ij['names'][name]} (`ironjetpacks:jetpack`, tipo `{name}`) | Iron Jetpacks 8.0.11 | "
                     f"`{ij['field']}`, {ij['unit']} | {value} | {raised(value, factor)} |")
    for entry in data['configs']:
        settings = entry['settings']
        keys = '; '.join(f"`{key}`, {unit}" for key, (_, unit) in settings.items())
        before = '; '.join(str(default) for default, _ in settings.values())
        after = '; '.join(str(raised(default, factor)) for default, _ in settings.values())
        lines.append(f"| {entry['name']} (`{entry['item']}`) | {entry['mod']} | {keys} en `{entry['file']}` | "
                     f"{before} | {after} |")
    for row in data['surcharge']['items']:
        lines.append(f"| {row['name']} (`{row['item']}`) | {row['mod']} | fijo en el código; recargo del script | "
                     f"{row['before']} | {row['after']} |")
    lines += ['', END]
    return '\n'.join(lines)


def outputs(data: dict) -> dict[str, str]:
    factor = Fraction(data['factor'])
    files = {}
    files.update(iron_jetpacks(data, factor))
    files.update(configs(data, factor))
    files[data['surcharge']['script']] = script(data, factor)
    return files


def doc_with_table(data: dict) -> str:
    text = DOC.read_text(encoding='utf-8')
    if START not in text or END not in text:
        raise SystemExit(f'{DOC.relative_to(ROOT)} lacks the {START} ... {END} markers')
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return head + table(data, Fraction(data['factor'])) + tail


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = load()
    files = outputs(data)
    files[DOC.relative_to(ROOT).as_posix()] = doc_with_table(data)
    folder = ROOT / 'pack/config/ironjetpacks/jetpacks'
    shipped = {p.relative_to(ROOT).as_posix() for p in folder.glob('*.json')} if folder.is_dir() else set()
    extra = shipped - set(files)
    stale = [name for name, text in files.items()
             if not (ROOT / name).is_file() or (ROOT / name).read_text(encoding='utf-8') != text]
    if args.check:
        problems = [f'stale: {name}' for name in stale] + [f'not generated: {name}' for name in sorted(extra)]
        for problem in problems:
            print(problem)
        print(f"jetpack balance: {len(files)} files, factor {data['factor']}, "
              f"{'OK' if not problems else str(len(problems)) + ' problem(s)'}")
        return 1 if problems else 0
    if extra:
        raise SystemExit('Unexpected Iron Jetpacks types in the pack: ' + ', '.join(sorted(extra)))
    for name in stale:
        target = ROOT / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(files[name], encoding='utf-8', newline='\n')
        print('wrote', name)
    print(f'jetpack balance: {len(files)} files, {len(stale)} written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
